package cn.jia.chat.api;

import cn.jia.agent.entity.ControlledImageFollowupAuthorityDTO;
import cn.jia.agent.service.ControlledImageFollowupAuthorityService;
import cn.jia.chat.service.CanonicalContextJson;
import tools.jackson.core.StreamReadFeature;
import tools.jackson.databind.*;
import tools.jackson.databind.json.JsonMapper;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

/** Strict schema-3 owner wire. Browser values never include server source lineage or authority facts. */
public final class ChatBountyInteractionV3Wire {
 private ChatBountyInteractionV3Wire(){}
 private static final long SAFE=9_007_199_254_740_991L;
 private static final ObjectMapper JSON=JsonMapper.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS).build();
 private static final Set<String> INTENT=Set.of("schemaVersion","interactionKind","taskId","expectedConversationGeneration","expectedTaskVersion","expectedAssignmentRevision","expectedGrantVersion","requirementRevision","targetAgentId","content","actionProposal","inputRefs","replyTo","continuationOf");
 private static final Set<String> ADMIT=new HashSet<>(){{addAll(INTENT);add("authority");}};
 public record AssetRef(String assetId,long revision) { }
 public record InputRef(String kind,String fileId,Integer version,String purpose,AssetRef assetRef) { }
 public record Parent(String requestId,String stepId) { }
 public record Authority(String consentId,long expectedConsentVersion,String operationGrantId,long expectedOperationGrantVersion) { }
 public record IntentValue(String taskId,long conversationGeneration,long taskVersion,long assignmentRevision,long grantVersion,long requirementRevision,String targetAgentId,String content,String operation,List<InputRef> inputRefs,Parent continuationOf,Authority authority,Map<String,Object> canonicalOwner) { public IntentValue{inputRefs=List.copyOf(inputRefs);canonicalOwner=Collections.unmodifiableMap(new LinkedHashMap<>(canonicalOwner));} }
 public record ExpectedPreview(String ownerPayloadSha256,String instructionSha256,String sourceSnapshotSha256,String modelId,String custody,String operatorPolicyRevision) { }
 public record Issue(String interactionIdempotencyKey,IntentValue intent,String bindingId,long bindingEpoch,ExpectedPreview expectedPreview,String acknowledgement,Map<String,Object> canonical) { }
 public record ContextData(int schemaVersion,String conversationId,String conversationGeneration,
   String taskId,String targetAgentId,String taskVersion,String assignmentRevision,
   String baselineGrantVersion,String requirementRevision) { }
 public record PreviewData(int schemaVersion,String requestId,String stepId,String executionIntentId,String ownerPayloadSha256,String instructionSha256,String sourceSnapshotSha256,String conversationGeneration,String taskVersion,String assignmentRevision,String grantVersion,String requirementRevision,String targetAgentId,String operation,List<ControlledImageFollowupAuthorityDTO.Source> sources,ControlledImageFollowupAuthorityDTO.ProviderBinding providerBinding,String modelId,String custody,String operatorPolicyRevision,String pricingMode,int maxOutboundRequestAttempts) { }
 public record AcceptedData(int schemaVersion,String requestId,String userMessageId,String stepId,String executionIntentId,String consentId,String operationGrantId,String state,String stateVersion,String eventCursor,String statusUrl,boolean replay) { }
 public record RevokeBody(String operationGrantId,long expectedConsentVersion,long expectedOperationGrantVersion) { }

 public static IntentValue parseIntent(String raw,boolean authorityRequired){JsonNode n=read(raw);Set<String> expected=authorityRequired?ADMIT:INTENT;if(!n.isObject()||!fields(n).equals(expected)||!integer(n,"schemaVersion",3)||!"EXECUTE".equals(text(n,"interactionKind",20)))throw bad();String task=id(text(n,"taskId",100),100);long generation=decimal(n,"expectedConversationGeneration",1);long taskVersion=decimal(n,"expectedTaskVersion",0);long assignment=decimal(n,"expectedAssignmentRevision",0);long grant=decimal(n,"expectedGrantVersion",1);long requirement=decimal(n,"requirementRevision",1);String target=id(text(n,"targetAgentId",100),100);String content=text(n,"content",4000);if(content.isBlank()||content.chars().anyMatch(Character::isISOControl))throw bad();JsonNode action=n.get("actionProposal");if(action==null||!action.isObject()||!fields(action).equals(Set.of("kind")))throw bad();String operation=switch(text(action,"kind",30)){case "generate_image"->"GENERATE_IMAGE";case "edit_image"->"EDIT_IMAGE";default->throw bad();};if(!n.get("replyTo").isNull())throw bad();Parent parent=parseParent(n.get("continuationOf"),"EDIT_IMAGE".equals(operation));List<InputRef> refs=parseRefs(n.get("inputRefs"),operation);Authority authority=authorityRequired?parseAuthority(n.get("authority")):null;Map<String,Object> owner=ownerMap(task,generation,taskVersion,assignment,grant,requirement,target,content,operation,refs,parent);return new IntentValue(task,generation,taskVersion,assignment,grant,requirement,target,content,operation,refs,parent,authority,owner);}
 public static Issue parseIssue(String raw){JsonNode n=read(raw);if(!n.isObject()||!fields(n).equals(Set.of("schemaVersion","interactionIdempotencyKey","intent","providerBinding","expectedPreview","acknowledgement"))||!integer(n,"schemaVersion",2))throw bad();String key=id(text(n,"interactionIdempotencyKey",100),100);IntentValue intent=parseIntent(n.get("intent").toString(),false);JsonNode binding=n.get("providerBinding");if(binding==null||!binding.isObject()||!fields(binding).equals(Set.of("bindingId","bindingEpoch")))throw bad();String bindingId=id(text(binding,"bindingId",100),100);long epoch=decimal(binding,"bindingEpoch",1);JsonNode expected=n.get("expectedPreview");if(expected==null||!expected.isObject()||!fields(expected).equals(Set.of("ownerPayloadSha256","instructionSha256","sourceSnapshotSha256","modelId","custody","operatorPolicyRevision")))throw bad();ExpectedPreview ep=new ExpectedPreview(hash(text(expected,"ownerPayloadSha256",64)),hash(text(expected,"instructionSha256",64)),hash(text(expected,"sourceSnapshotSha256",64)),id(text(expected,"modelId",100),100),id(text(expected,"custody",50),50),id(text(expected,"operatorPolicyRevision",100),100));String ack=text(n,"acknowledgement",100);Map<String,Object> canonical=new LinkedHashMap<>();canonical.put("acknowledgement",ack);canonical.put("expectedPreview",Map.of("custody",ep.custody(),"instructionSha256",ep.instructionSha256(),"modelId",ep.modelId(),"operatorPolicyRevision",ep.operatorPolicyRevision(),"ownerPayloadSha256",ep.ownerPayloadSha256(),"sourceSnapshotSha256",ep.sourceSnapshotSha256()));canonical.put("interactionIdempotencyKey",key);canonical.put("intent",intent.canonicalOwner());canonical.put("providerBinding",Map.of("bindingEpoch",Long.toString(epoch),"bindingId",bindingId));canonical.put("schemaVersion",2);return new Issue(key,intent,bindingId,epoch,ep,ack,Map.copyOf(canonical));}
 public static Map<String,Object> canonicalAdmit(IntentValue intent){
  if(intent==null||intent.authority()==null)throw bad();Map<String,Object> m=new LinkedHashMap<>(intent.canonicalOwner());
  Authority a=intent.authority();m.put("authority",Map.of("consentId",a.consentId(),"expectedConsentVersion",Long.toString(a.expectedConsentVersion()),"operationGrantId",a.operationGrantId(),"expectedOperationGrantVersion",Long.toString(a.expectedOperationGrantVersion())));return Collections.unmodifiableMap(new LinkedHashMap<>(m));
 }
 public static int schemaVersion(String raw){JsonNode n=read(raw);JsonNode v=n.get("schemaVersion");if(v==null||!v.isIntegralNumber()||!v.canConvertToInt())throw bad();return v.intValue();}
 public static RevokeBody parseRevoke(String raw){JsonNode n=read(raw);if(!n.isObject()||!fields(n).equals(Set.of("schemaVersion","operationGrantId","expectedConsentVersion","expectedOperationGrantVersion"))||!integer(n,"schemaVersion",2))throw bad();return new RevokeBody(id(text(n,"operationGrantId",100),100),decimal(n,"expectedConsentVersion",1),decimal(n,"expectedOperationGrantVersion",1));}
 public static String sha(Object value){return shaText(CanonicalContextJson.write(value));}
 public static String instructionSha(String instruction){return sha(Map.of("instruction",instruction,"schemaVersion",1));}
 public static String shaText(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private static Map<String,Object> ownerMap(String task,long generation,long taskVersion,long assignment,long grant,long requirement,String target,String content,String operation,List<InputRef> refs,Parent parent){Map<String,Object> m=new LinkedHashMap<>();m.put("actionProposal",Map.of("kind","GENERATE_IMAGE".equals(operation)?"generate_image":"edit_image"));m.put("content",content);m.put("continuationOf",parent==null?null:Map.of("requestId",parent.requestId(),"stepId",parent.stepId()));m.put("expectedAssignmentRevision",Long.toString(assignment));m.put("expectedConversationGeneration",Long.toString(generation));m.put("expectedGrantVersion",Long.toString(grant));m.put("expectedTaskVersion",Long.toString(taskVersion));List<Map<String,Object>> inputs=new ArrayList<>();for(InputRef r:refs){if(r.assetRef()!=null)inputs.add(Map.of("assetRef",Map.of("assetId",r.assetRef().assetId(),"revision",Long.toString(r.assetRef().revision())),"kind",r.kind()));else inputs.add(Map.of("fileId",r.fileId(),"kind",r.kind(),"purpose",r.purpose(),"version",Integer.toString(r.version())));}m.put("inputRefs",inputs);m.put("interactionKind","EXECUTE");m.put("replyTo",null);m.put("requirementRevision",Long.toString(requirement));m.put("schemaVersion",3);m.put("targetAgentId",target);m.put("taskId",task);return m;}
 private static List<InputRef> parseRefs(JsonNode n,String operation){if(n==null||!n.isArray()||n.size()>16)throw bad();List<InputRef> out=new ArrayList<>();for(JsonNode r:n){if(r==null||!r.isObject())throw bad();String kind=text(r,"kind",50);if("GENERATE_IMAGE".equals(operation)){if(!fields(r).equals(Set.of("kind","fileId","version","purpose"))||!"TASK_LINKED_WORKSPACE_VERSION".equals(kind)||!"REFERENCE".equals(text(r,"purpose",20)))throw bad();long version=decimal(r,"version",1);if(version>Integer.MAX_VALUE)throw bad();out.add(new InputRef(kind,id(text(r,"fileId",100),100),(int)version,"REFERENCE",null));}else{if(!fields(r).equals(Set.of("kind","assetRef"))||!"CURRENT_CONVERSATION_ASSET".equals(kind))throw bad();JsonNode a=r.get("assetRef");if(a==null||!a.isObject()||!fields(a).equals(Set.of("assetId","revision")))throw bad();out.add(new InputRef(kind,null,null,null,new AssetRef(id(text(a,"assetId",100),100),decimal(a,"revision",1))));}}if("EDIT_IMAGE".equals(operation)&&out.size()!=1)throw bad();return List.copyOf(out);}
 private static Parent parseParent(JsonNode n,boolean required){if(n==null||n.isNull()){if(required)throw bad();return null;}if(!n.isObject()||!fields(n).equals(Set.of("requestId","stepId")))throw bad();return new Parent(id(text(n,"requestId",100),100),id(text(n,"stepId",100),100));}
 private static Authority parseAuthority(JsonNode n){if(n==null||!n.isObject()||!fields(n).equals(Set.of("consentId","expectedConsentVersion","operationGrantId","expectedOperationGrantVersion")))throw bad();String consent=id(text(n,"consentId",100),100);String op=id(text(n,"operationGrantId",100),100);if(!consent.matches("consent_[0-9a-f]{32}")||!op.matches("opgrant_[0-9a-f]{32}"))throw bad();return new Authority(consent,decimal(n,"expectedConsentVersion",1),op,decimal(n,"expectedOperationGrantVersion",1));}
 private static JsonNode read(String raw){try{if(raw==null||raw.isBlank())throw bad();return JSON.readTree(raw);}catch(RuntimeException e){throw e;}catch(Exception e){throw bad();}}
 private static boolean integer(JsonNode n,String key,int expected){JsonNode v=n.get(key);return v!=null&&v.isIntegralNumber()&&v.canConvertToInt()&&v.intValue()==expected;}
 private static long decimal(JsonNode n,String key,long min){JsonNode v=n.get(key);if(v==null||!v.isTextual()||!v.textValue().matches(min==0?"0|[1-9][0-9]*":"[1-9][0-9]*"))throw bad();try{long x=Long.parseLong(v.textValue());if(x<min||x>SAFE||!Long.toString(x).equals(v.textValue()))throw bad();return x;}catch(NumberFormatException e){throw bad();}}
 private static String text(JsonNode n,String key,int max){JsonNode v=n.get(key);if(v==null||!v.isTextual()||v.textValue().codePointCount(0,v.textValue().length())>max)return badValue();return v.textValue();}
 private static String id(String v,int max){if(v==null||v.isBlank()||!v.equals(v.strip())||v.codePointCount(0,v.length())>max||v.chars().anyMatch(Character::isISOControl))throw bad();return v;}
 private static String hash(String v){if(v==null||!v.matches("[0-9a-f]{64}"))throw bad();return v;}
 private static Set<String> fields(JsonNode n){Set<String> out=new HashSet<>();n.propertyNames().forEach(out::add);return out;}
 private static <T>T badValue(){throw bad();}private static IllegalArgumentException bad(){return new IllegalArgumentException("BOUNTY_FOLLOWUP_V3_INVALID_REQUEST");}
}
