spring.application.name=jia-mcp-server
spring.main.banner-mode=off

spring.main.web-application-type=none
spring.ai.mcp.server.name=jia-mcp-database-tool
spring.ai.mcp.server.version=1.0.0

# MySQL Configuration
spring.datasource.url=jdbc:mysql://47.106.106.57:3306/jia_dev?useUnicode=true&generateSimpleParameterMetadata=true&characterEncoding=utf-8
spring.datasource.username = ENC(eZ+ev8ac6+SZHL4Y1zSEIAKHChJONtmiE9furv4dSYxf0XL/0V4jW5RhuvpuaJ7o)
spring.datasource.password = ENC(Gi1LoYxTLm0kigMcp+RXnY9thYON7eL9Ufub6qMlPK75ZA8C3AyVx082nlf0/JtK)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection pool settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10

# Logging Configuration
logging.level.root=ERROR
