server.port=10121

spring.application.name=jia-agent-service
spring.main.banner-mode=off
# spring.main.web-application-type=none

#数据库配置
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://47.106.106.57:3306/jia_dev?useUnicode=true&generateSimpleParameterMetadata=true&characterEncoding=utf-8
spring.datasource.username = ENC(eZ+ev8ac6+SZHL4Y1zSEIAKHChJONtmiE9furv4dSYxf0XL/0V4jW5RhuvpuaJ7o)
spring.datasource.password = ENC(Gi1LoYxTLm0kigMcp+RXnY9thYON7eL9Ufub6qMlPK75ZA8C3AyVx082nlf0/JtK)

spring.ai.model.chat=deepseek
spring.ai.model.embedding=zhipuai

spring.ai.vectorstore.type=elasticsearch
# spring.ai.vectorstore.type=none

# ZhiPuAi configuration
spring.ai.zhipuai.api-key=ENC(G/y/lLwUQMai71gbTip+Xh1Sufx8R2KkooPMhWZjXYk+uMAm7IsK9Qv6aHXtdoXfTUrRTrGSQH6LF/1Jt20wwwpWwOEStXN2YucictxUzkS8LyapNv7DI1KSUSZMIAyx)
spring.ai.zhipuai.base-url=https://open.bigmodel.cn/api/paas
spring.ai.zhipuai.chat.options.model=glm-4
spring.ai.zhipuai.embedding.options.model=embedding-3

# Deepseek configuration
spring.ai.deepseek.api-key=ENC(WR6dwgEKI07XVAYmq/Yr0fyLCYl18Ri9W/dQhQcX+lLTvZlxDc2gJXi3jIv9Qmu+8xo6erm+hQ8RtC4FwIFKN/7FjOgLVtDvpyHDkigxUIU=)
spring.ai.deepseek.base-url=https://api.deepseek.com
spring.ai.deepseek.chat.options.model=deepseek-chat

# Enable Ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:0.6b
spring.ai.ollama.embedding.options.model=qwen3:0.6b

spring.ai.mcp.client.name=jia-agent-service
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.toolcallback.enabled=true
# 设置 MCP 客户端全局超时时间为 60 秒
spring.ai.mcp.client.request-timeout=60s
#spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers-config.json

# MCP servers configuration
spring.ai.mcp.client.stdio.connections.filesystem.command=cmd
spring.ai.mcp.client.stdio.connections.filesystem.args[0]=/c
spring.ai.mcp.client.stdio.connections.filesystem.args[1]=npx
spring.ai.mcp.client.stdio.connections.filesystem.args[2]=-y
spring.ai.mcp.client.stdio.connections.filesystem.args[3]=@modelcontextprotocol/server-filesystem
spring.ai.mcp.client.stdio.connections.filesystem.args[4]=.

spring.ai.mcp.client.stdio.connections.time.command=uvx
spring.ai.mcp.client.stdio.connections.time.args[0]=mcp-server-time
spring.ai.mcp.client.stdio.connections.time.args[1]=--local-timezone=Asia/Shanghai

spring.ai.mcp.client.stdio.connections.mysql.command=uv
spring.ai.mcp.client.stdio.connections.mysql.args[0]=--directory
spring.ai.mcp.client.stdio.connections.mysql.args[1]=D:/software/Python/Lib/site-packages/mysql_mcp_server
spring.ai.mcp.client.stdio.connections.mysql.args[2]=run
spring.ai.mcp.client.stdio.connections.mysql.args[3]=mysql_mcp_server
spring.ai.mcp.client.stdio.connections.mysql.env.MYSQL_HOST=47.106.106.57
spring.ai.mcp.client.stdio.connections.mysql.env.MYSQL_PORT=3306
spring.ai.mcp.client.stdio.connections.mysql.env.MYSQL_USER=ENC(eZ+ev8ac6+SZHL4Y1zSEIAKHChJONtmiE9furv4dSYxf0XL/0V4jW5RhuvpuaJ7o)
spring.ai.mcp.client.stdio.connections.mysql.env.MYSQL_PASSWORD=ENC(Gi1LoYxTLm0kigMcp+RXnY9thYON7eL9Ufub6qMlPK75ZA8C3AyVx082nlf0/JtK)
spring.ai.mcp.client.stdio.connections.mysql.env.MYSQL_DATABASE=jia_dev

spring.ai.mcp.client.stdio.connections.sequential-thinking.command=npx
spring.ai.mcp.client.stdio.connections.sequential-thinking.args[0]=-y
spring.ai.mcp.client.stdio.connections.sequential-thinking.args[1]=@modelcontextprotocol/server-sequential-thinking
# 增加超时时间到 60 秒，避免初始化超时
spring.ai.mcp.client.stdio.connections.sequential-thinking.connection-timeout=60s

spring.ai.mcp.client.sse.connections.websearch.url=https://open.bigmodel.cn
spring.ai.mcp.client.sse.connections.websearch.sse-endpoint=/api/mcp/web_search/sse?Authorization=${spring.ai.zhipuai.api-key}

agent.skills.dirs=C:/Users/Think/.openclaw/skills,D:/workspace/chcbz/agent-skills

logging.level.root=INFO
logging.level.co.elastic.clients=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.org.apache.http.wire=DEBUG
logging.level.org.springframework.ai=DEBUG

# Redis Vector Store Configuration
spring.data.redis.database=2
spring.data.redis.host=47.106.106.57
spring.data.redis.port=6379
spring.data.redis.password=ENC(zRiX657DSoedZzTts525Th5qiBRb9H9XE4aZK38YDcyZfLfhXuSkeErT7pn5bdqs)
spring.ai.vectorstore.redis.initialize-schema=true
spring.ai.vectorstore.redis.index-name=agent_dev
spring.ai.vectorstore.redis.prefix=doc:

# Elasticsearch Vector Store Configuration
spring.elasticsearch.uris=47.106.106.57:9200
spring.elasticsearch.username=ENC(eZ+ev8ac6+SZHL4Y1zSEIAKHChJONtmiE9furv4dSYxf0XL/0V4jW5RhuvpuaJ7o)
spring.elasticsearch.password=ENC(Gi1LoYxTLm0kigMcp+RXnY9thYON7eL9Ufub6qMlPK75ZA8C3AyVx082nlf0/JtK)
spring.elasticsearch.connection-timeout=60s
spring.elasticsearch.socket-timeout=60s
# {"mappings":{"properties":{"text":{"type":"text","analyzer":"ik\_max\_word","search\_analyzer":"ik\_smart"},"userId":{"type":"keyword"},"conversationId":{"type":"keyword"},"timestamp":{"type":"date"},"role":{"type":"keyword"},"embedding":{"type":"dense\_vector","dims":2560,"index":true,"similarity":"cosine"}}}}
spring.ai.vectorstore.elasticsearch.initialize-schema=false
spring.ai.vectorstore.elasticsearch.index-name=agent_dev
spring.ai.vectorstore.elasticsearch.dimensions=2048
spring.ai.vectorstore.elasticsearch.similarity=cosine
spring.ai.vectorstore.elasticsearch.initialize-schema-timeout=60s

spring.jackson.time-zone=Asia/Shanghai
