dependencies {
    api project(':common:jia-common-core')
    api(libs.swagger.annotations)
    api(libs.mybatis.plus.annotation)
    api 'com.fasterxml.jackson.core:jackson-databind:2.18.3'
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

version = '1.1.2-SNAPSHOT'
description = 'jia-chat-core'