spring.application.name=jia-oauth
server.port=10101

#数据库配置
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://47.106.106.57:3306/jia_dev?useUnicode=true&generateSimpleParameterMetadata=true&characterEncoding=utf-8
spring.datasource.username = ENC(eZ+ev8ac6+SZHL4Y1zSEIAKHChJONtmiE9furv4dSYxf0XL/0V4jW5RhuvpuaJ7o)
spring.datasource.password = ENC(Gi1LoYxTLm0kigMcp+RXnY9thYON7eL9Ufub6qMlPK75ZA8C3AyVx082nlf0/JtK)

#LDAP配置
spring.ldap.urls=ldap://ldap.chcbz.net:389
spring.ldap.username=cn=root,ou=api-dev,dc=jia,dc=cn
spring.ldap.password=ENC(t/OYtwFPaT8GyNrL1QavdlGWo4ClqvBCvEqM8tS7wrLM8dUpIHoBmanxaZEc2Cug)
spring.ldap.base=ou=api-dev,dc=jia,dc=cn
spring.ldap.baseEnvironment[java.naming.ldap.attributes.binary]=headimg logo logoIcon

# Elasticsearch配置
spring.elasticsearch.uris=47.106.106.57:9200
spring.elasticsearch.username=ENC(eZ+ev8ac6+SZHL4Y1zSEIAKHChJONtmiE9furv4dSYxf0XL/0V4jW5RhuvpuaJ7o)
spring.elasticsearch.password=ENC(Gi1LoYxTLm0kigMcp+RXnY9thYON7eL9Ufub6qMlPK75ZA8C3AyVx082nlf0/JtK)
phrase.elasticsearch.index=phrase_dev

#日志配置
logging.level.root=debug
logging.level.cn.jia=debug
logging.level.org.springframework=debug
logging.level.org.springframework.web=debug
logging.level.org.springframework.transaction=debug
logging.level.org.springframework.amqp=info
logging.level.org.mybatis=debug
logging.level.druid.sql=debug

#oauth.permit.uris[0]=/**/*.html

oauth.third-party.wxmp.appid=ENC(97um46gfXB0pQLTcVf2efEOSEY5Qq8dSi+h5WD3C1pRD0RphpYA8opEcJlySnp8uPryZbeg1t1RKyWIHs1BbXw==)
oauth.third-party.wxmp.secret=ENC(3mGbtN4Y/1LwN80OfoNvZiXlYs8PaKMCUHCQ1TAWgSm7dZ8WoFe4Z0d0Wem10NX5CB/NpG8DyIEdkDWFKmBuQGHXVQOsxR8Y/wHyB10Fyi8=)
oauth.third-party.weixin.appid=ENC(qLX/SdKA7SyroHd62TXWLIk1iH/Y42h278x2SiZS1IMhlqurRqcs7Wk31no9sdUosMOmcby2JLG0doU+tu4HqQ==)
oauth.third-party.weixin.secret=ENC(bk3cy7B8G1mYmGYuhNpXURhRrtBE9BLA1WGWlcz8jsLKgMcg5qvt0/bJtVLVN1ski8glqNMtcqFcOPBO/9sR/jHTEJDfmoERRRlR/vyKFd8=)
oauth.third-party.weibo.appid=ENC(BEVDS8kyzwvPlxkqCTxeGkOqjFLmyEAzoZsAbsFDd84cbju+0dXdvNAXckhydyg8)
oauth.third-party.weibo.secret=ENC(C8Uyi7JLBpRSYZ1Ka5TciA61RE5dnN2/jbCLVh9vk9kejZUPUSrNKRdeLNcn5x2VGeDOL9rimzF89RHcIgtP8h6kM5J7yTPqvNgj5KhDyKU=)