CREATE TABLE archive_question (
    row_id                    BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id                 VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id                 VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn               VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    question_id               CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    edition_id                VARCHAR(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    edition_manifest_sha256   CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    block_type                VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    block_id                  VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    anchor_json               LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    selected_text             LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    question_text             LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    status                    VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    responder_id              VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    responder_name            VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    responder_mode            VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    answer                    LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    retry_count               INT NOT NULL,
    last_error_code           VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    version                   BIGINT NOT NULL,
    current_sequence          BIGINT NOT NULL,
    created_at                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    completed_at              TIMESTAMP(6) NULL,
    PRIMARY KEY (row_id),
    UNIQUE KEY uk_archive_question_owner_id (tenant_id, client_id, owner_jiacn, question_id),
    UNIQUE KEY uk_archive_question_row_owner (row_id, tenant_id, client_id, owner_jiacn, question_id),
    KEY idx_archive_question_owner_created (tenant_id, client_id, owner_jiacn, created_at, row_id),
    KEY idx_archive_question_content (edition_id, block_id),
    CONSTRAINT chk_archive_question_id CHECK (question_id REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
    CONSTRAINT chk_archive_question_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED_RETRYABLE', 'FAILED_FINAL')),
    CONSTRAINT chk_archive_question_content CHECK (edition_manifest_sha256 REGEXP '^[0-9a-f]{64}$' AND block_type IN ('PREFACE', 'CHAPTER') AND JSON_VALID(anchor_json)),
    CONSTRAINT chk_archive_question_responder CHECK (responder_id = 'archive-clerk-v1' AND responder_name = CONVERT(0xE6A188E58DB7E4B9A6E5908F USING utf8mb4) AND responder_mode = 'fallback'),
    CONSTRAINT chk_archive_question_lengths CHECK (OCTET_LENGTH(selected_text) BETWEEN 1 AND 8192 AND OCTET_LENGTH(question_text) BETWEEN 1 AND 8192 AND OCTET_LENGTH(answer) <= 131072),
    CONSTRAINT chk_archive_question_counters CHECK (retry_count BETWEEN 0 AND 2 AND version >= 1 AND current_sequence >= 1),
    CONSTRAINT chk_archive_question_terminal CHECK (((status IN ('SUCCEEDED', 'FAILED_FINAL')) AND completed_at IS NOT NULL) OR ((status IN ('QUEUED', 'RUNNING', 'FAILED_RETRYABLE')) AND completed_at IS NULL)),
    CONSTRAINT chk_archive_question_error CHECK (((status IN ('FAILED_RETRYABLE', 'FAILED_FINAL')) AND last_error_code IS NOT NULL AND last_error_code REGEXP '^[A-Z][A-Z0-9_]{0,63}$') OR ((status IN ('QUEUED', 'RUNNING', 'SUCCEEDED')) AND last_error_code IS NULL)),
    CONSTRAINT chk_archive_question_queued_answer CHECK (status <> 'QUEUED' OR answer = ''),
    CONSTRAINT fk_archive_question_edition FOREIGN KEY (edition_id) REFERENCES archive_edition (edition_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_archive_question_block FOREIGN KEY (edition_id, block_id)
        REFERENCES archive_chapter (edition_id, block_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE archive_question_mutation (
    row_id                    BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id                 VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id                 VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn               VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    question_id               CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    http_method               VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    canonical_path            VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    idempotency_key           VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_sha256            CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state                     VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    question_row_id           BIGINT NULL,
    response_status           INT NULL,
    response_content_type     VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    response_body             LONGBLOB NULL,
    created_at                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at                TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (row_id),
    UNIQUE KEY uk_archive_question_mutation_scope (tenant_id, client_id, owner_jiacn, http_method, canonical_path, idempotency_key),
    KEY idx_archive_question_mutation_expiry (expires_at, row_id),
    KEY idx_archive_question_mutation_question (question_row_id, tenant_id, client_id, owner_jiacn, question_id),
    CONSTRAINT chk_archive_question_mutation_id CHECK (question_id REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
    CONSTRAINT chk_archive_question_mutation_method CHECK (http_method IN ('PUT', 'POST')),
    CONSTRAINT chk_archive_question_mutation_path CHECK (canonical_path REGEXP '^[!-~]{1,512}$' AND ((http_method = 'PUT' AND canonical_path = CONCAT('/archive/v1/me/questions/', question_id)) OR (http_method = 'POST' AND canonical_path = CONCAT('/archive/v1/me/questions/', question_id, '/retry')))),
    CONSTRAINT chk_archive_question_mutation_hash CHECK (request_sha256 REGEXP '^[0-9a-f]{64}$'),
    CONSTRAINT chk_archive_question_mutation_state CHECK (state IN ('PENDING', 'COMPLETED')),
    CONSTRAINT chk_archive_question_mutation_key CHECK (idempotency_key REGEXP '^[!-~]{1,128}$'),
    CONSTRAINT chk_archive_question_mutation_response CHECK ((state = 'PENDING' AND question_row_id IS NULL AND response_status IS NULL AND response_content_type IS NULL AND response_body IS NULL) OR (state = 'COMPLETED' AND question_row_id IS NOT NULL AND response_status = 202 AND response_content_type IS NOT NULL AND response_body IS NOT NULL)),
    CONSTRAINT chk_archive_question_mutation_expiry CHECK (expires_at >= created_at),
    CONSTRAINT fk_archive_question_mutation_question FOREIGN KEY (question_row_id, tenant_id, client_id, owner_jiacn, question_id)
        REFERENCES archive_question (row_id, tenant_id, client_id, owner_jiacn, question_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE archive_question_event (
    row_id                    BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id                 VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id                 VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn               VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    question_id               CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    sequence                  BIGINT NOT NULL,
    event_type                VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    payload_json              LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    occurred_at               TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (row_id),
    UNIQUE KEY uk_archive_question_event_sequence (tenant_id, client_id, owner_jiacn, question_id, sequence),
    KEY idx_archive_question_event_replay (tenant_id, client_id, owner_jiacn, question_id, sequence, row_id),
    CONSTRAINT chk_archive_question_event_id CHECK (question_id REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
    CONSTRAINT chk_archive_question_event_sequence CHECK (sequence >= 1),
    CONSTRAINT chk_archive_question_event_type CHECK (event_type IN ('QUESTION_QUEUED', 'QUESTION_RUNNING', 'ANSWER_DELTA', 'QUESTION_SUCCEEDED', 'QUESTION_FAILED_RETRYABLE', 'QUESTION_FAILED_FINAL', 'QUESTION_RETRY_QUEUED')),
    CONSTRAINT chk_archive_question_event_payload CHECK (JSON_VALID(payload_json) AND OCTET_LENGTH(payload_json) BETWEEN 2 AND 32768),
    CONSTRAINT fk_archive_question_event_question FOREIGN KEY (tenant_id, client_id, owner_jiacn, question_id)
        REFERENCES archive_question (tenant_id, client_id, owner_jiacn, question_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE archive_outbox (
    row_id                    BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id                 VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id                 VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn               VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    question_id               CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state                     VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    attempt_count             INT NOT NULL,
    fencing_token             BIGINT NOT NULL,
    published_sequence        BIGINT NOT NULL,
    available_at              TIMESTAMP(6) NOT NULL,
    lease_until               TIMESTAMP(6) NULL,
    last_error_code           VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    created_at                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (row_id),
    UNIQUE KEY uk_archive_outbox_question (tenant_id, client_id, owner_jiacn, question_id),
    KEY idx_archive_outbox_claim (state, available_at, lease_until, row_id),
    KEY idx_archive_outbox_publish (published_sequence, row_id),
    CONSTRAINT chk_archive_outbox_id CHECK (question_id REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
    CONSTRAINT chk_archive_outbox_state CHECK (state IN ('READY', 'LEASED', 'WAITING_RETRY', 'DONE')),
    CONSTRAINT chk_archive_outbox_counters CHECK (attempt_count BETWEEN 0 AND 3 AND fencing_token >= 0 AND published_sequence >= 0),
    CONSTRAINT chk_archive_outbox_lease CHECK ((state = 'LEASED' AND lease_until IS NOT NULL) OR (state IN ('READY', 'WAITING_RETRY', 'DONE') AND lease_until IS NULL)),
    CONSTRAINT chk_archive_outbox_error CHECK ((state IN ('READY', 'LEASED') AND last_error_code IS NULL) OR (state = 'WAITING_RETRY' AND last_error_code IS NOT NULL AND last_error_code REGEXP '^[A-Z][A-Z0-9_]{0,63}$') OR (state = 'DONE' AND (last_error_code IS NULL OR last_error_code REGEXP '^[A-Z][A-Z0-9_]{0,63}$'))),
    CONSTRAINT fk_archive_outbox_question FOREIGN KEY (tenant_id, client_id, owner_jiacn, question_id)
        REFERENCES archive_question (tenant_id, client_id, owner_jiacn, question_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
