package cn.jia.agent.mapper;
import cn.jia.agent.entity.ControlledImageIntentOperationGrantEntity;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.*;
public interface ControlledImageIntentOperationGrantMapper extends BaseMapper<ControlledImageIntentOperationGrantEntity> {
 String S="tenant_id=#{tenant} AND client_id=#{client} AND owner_jiacn=#{owner} AND task_id=#{task} AND CAST(tenant_id AS BINARY)=CAST(#{tenant} AS BINARY) AND CAST(client_id AS BINARY)=CAST(#{client} AS BINARY) AND CAST(owner_jiacn AS BINARY)=CAST(#{owner} AS BINARY) AND CAST(task_id AS BINARY)=CAST(#{task} AS BINARY)";
 @Select("SELECT * FROM agent_controlled_image_intent_operation_grant WHERE "+S+" AND issue_idempotency_key=#{key} AND CAST(issue_idempotency_key AS BINARY)=CAST(#{key} AS BINARY) LIMIT 1")
 ControlledImageIntentOperationGrantEntity byIssue(@Param("tenant")String tenant,@Param("client")String client,@Param("owner")String owner,@Param("task")String task,@Param("key")String key);
 @Select("SELECT * FROM agent_controlled_image_intent_operation_grant WHERE "+S+" AND issue_idempotency_key=#{key} AND CAST(issue_idempotency_key AS BINARY)=CAST(#{key} AS BINARY) LIMIT 1 FOR UPDATE")
 ControlledImageIntentOperationGrantEntity lockIssue(@Param("tenant")String tenant,@Param("client")String client,@Param("owner")String owner,@Param("task")String task,@Param("key")String key);
 @Select("SELECT * FROM agent_controlled_image_intent_operation_grant WHERE "+S+" AND interaction_idempotency_key=#{key} AND CAST(interaction_idempotency_key AS BINARY)=CAST(#{key} AS BINARY) LIMIT 1")
 ControlledImageIntentOperationGrantEntity byInteraction(@Param("tenant")String tenant,@Param("client")String client,@Param("owner")String owner,@Param("task")String task,@Param("key")String key);
 @Select("SELECT * FROM agent_controlled_image_intent_operation_grant WHERE "+S+" AND operation_grant_id=#{id} AND CAST(operation_grant_id AS BINARY)=CAST(#{id} AS BINARY) LIMIT 1")
 ControlledImageIntentOperationGrantEntity byId(@Param("tenant")String tenant,@Param("client")String client,@Param("owner")String owner,@Param("task")String task,@Param("id")String id);
 @Select("SELECT * FROM agent_controlled_image_intent_operation_grant WHERE "+S+" AND operation_grant_id=#{id} AND CAST(operation_grant_id AS BINARY)=CAST(#{id} AS BINARY) LIMIT 1 FOR UPDATE")
 ControlledImageIntentOperationGrantEntity lockId(@Param("tenant")String tenant,@Param("client")String client,@Param("owner")String owner,@Param("task")String task,@Param("id")String id);
 @Update("UPDATE agent_controlled_image_intent_operation_grant SET state='RESERVED',version=version+1,reserved_execution_id=#{r.reservedExecutionId},reserved_run_id=#{r.reservedRunId},update_time=#{r.updateTime} WHERE id=#{r.id} AND tenant_id=#{r.tenantId} AND client_id=#{r.clientId} AND owner_jiacn=#{r.ownerJiacn} AND task_id=#{r.taskId} AND operation_grant_id=#{r.operationGrantId} AND state='AUTHORIZED' AND version=#{v} AND CAST(tenant_id AS BINARY)=CAST(#{r.tenantId} AS BINARY) AND CAST(client_id AS BINARY)=CAST(#{r.clientId} AS BINARY) AND CAST(owner_jiacn AS BINARY)=CAST(#{r.ownerJiacn} AS BINARY) AND CAST(task_id AS BINARY)=CAST(#{r.taskId} AS BINARY) AND CAST(operation_grant_id AS BINARY)=CAST(#{r.operationGrantId} AS BINARY)") int reserve(@Param("r")ControlledImageIntentOperationGrantEntity row,@Param("v")long version);
 @Update("UPDATE agent_controlled_image_intent_operation_grant SET state='CONSUMED',version=version+1,consumed_lease_id=#{r.consumedLeaseId},update_time=#{r.updateTime} WHERE id=#{r.id} AND tenant_id=#{r.tenantId} AND client_id=#{r.clientId} AND owner_jiacn=#{r.ownerJiacn} AND task_id=#{r.taskId} AND operation_grant_id=#{r.operationGrantId} AND state='RESERVED' AND version=#{v} AND CAST(tenant_id AS BINARY)=CAST(#{r.tenantId} AS BINARY) AND CAST(client_id AS BINARY)=CAST(#{r.clientId} AS BINARY) AND CAST(owner_jiacn AS BINARY)=CAST(#{r.ownerJiacn} AS BINARY) AND CAST(task_id AS BINARY)=CAST(#{r.taskId} AS BINARY) AND CAST(operation_grant_id AS BINARY)=CAST(#{r.operationGrantId} AS BINARY)") int consume(@Param("r")ControlledImageIntentOperationGrantEntity row,@Param("v")long version);
 @Update("UPDATE agent_controlled_image_intent_operation_grant SET state='REVOKED',version=version+1,revoke_idempotency_key=#{r.revokeIdempotencyKey},revoke_request_digest=#{r.revokeRequestDigest},revoked_at=#{r.revokedAt},update_time=#{r.updateTime} WHERE id=#{r.id} AND tenant_id=#{r.tenantId} AND client_id=#{r.clientId} AND owner_jiacn=#{r.ownerJiacn} AND task_id=#{r.taskId} AND operation_grant_id=#{r.operationGrantId} AND state IN ('AUTHORIZED','RESERVED') AND version=#{v} AND CAST(tenant_id AS BINARY)=CAST(#{r.tenantId} AS BINARY) AND CAST(client_id AS BINARY)=CAST(#{r.clientId} AS BINARY) AND CAST(owner_jiacn AS BINARY)=CAST(#{r.ownerJiacn} AS BINARY) AND CAST(task_id AS BINARY)=CAST(#{r.taskId} AS BINARY) AND CAST(operation_grant_id AS BINARY)=CAST(#{r.operationGrantId} AS BINARY)") int revoke(@Param("r")ControlledImageIntentOperationGrantEntity row,@Param("v")long version);
}
