-- Prerequisite: retain the mode-600 preflight capture and its generated byte-exact rollback SQL.
-- This script fails closed unless exactly one byte-exact target exists, no folded/trailing collision exists, and its settings are valid JSON.
SET @asf_oauth_client_id := _ascii'jiafewnnv58ec2379c';
SET @asf_exact_target_count := (
  SELECT COUNT(*)
  FROM oauth_client
  WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(@asf_oauth_client_id)
    AND HEX(client_id) = HEX(@asf_oauth_client_id)
);
SET @asf_target_collision_count := (
  SELECT COUNT(*)
  FROM oauth_client
  WHERE client_id = @asf_oauth_client_id
    AND NOT (
      OCTET_LENGTH(client_id) = OCTET_LENGTH(@asf_oauth_client_id)
      AND HEX(client_id) = HEX(@asf_oauth_client_id)
    )
);
SET @asf_target_invalid_json_count := (
  SELECT COUNT(*)
  FROM oauth_client
  WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(@asf_oauth_client_id)
    AND HEX(client_id) = HEX(@asf_oauth_client_id)
    AND (client_settings IS NULL OR token_settings IS NULL
         OR NOT JSON_VALID(client_settings) OR NOT JSON_VALID(token_settings))
);
SET @asf_guard_sql := IF(
  @asf_exact_target_count = 1
  AND @asf_target_collision_count = 0
  AND @asf_target_invalid_json_count = 0,
  'SELECT ''oauth client migration guard passed'' AS account_security_migration',
  'SELECT * FROM account_security_foundation_migration_requires_one_byte_exact_oauth_client'
);
PREPARE asf_guard_stmt FROM @asf_guard_sql;
EXECUTE asf_guard_stmt;
DEALLOCATE PREPARE asf_guard_stmt;

UPDATE oauth_client
SET client_secret = NULL,
    client_secret_expires_at = NULL,
    client_authentication_methods = 'none',
    authorization_grant_types = 'authorization_code',
    redirect_uris = 'https://kit.chaoyoufan.cn/oauth2/callback',
    scopes = 'openid',
    client_settings = JSON_SET(client_settings,
        '$."settings.client.require-proof-key"', CAST('true' AS JSON)),
    token_settings = JSON_SET(token_settings,
        '$."settings.token.access-token-time-to-live"', 'PT10M',
        '$."settings.token.authorization-code-time-to-live"', 'PT5M')
WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(@asf_oauth_client_id)
  AND HEX(client_id) = HEX(@asf_oauth_client_id);

SELECT ROW_COUNT() AS migrated_target_client_rows;
SET @asf_postcondition_count := (
  SELECT COUNT(*)
  FROM oauth_client
  WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(@asf_oauth_client_id)
    AND HEX(client_id) = HEX(@asf_oauth_client_id)
    AND client_secret IS NULL
    AND client_secret_expires_at IS NULL
    AND OCTET_LENGTH(client_authentication_methods) = OCTET_LENGTH(_ascii'none')
    AND HEX(client_authentication_methods) = HEX(_ascii'none')
    AND OCTET_LENGTH(authorization_grant_types) = OCTET_LENGTH(_ascii'authorization_code')
    AND HEX(authorization_grant_types) = HEX(_ascii'authorization_code')
    AND OCTET_LENGTH(redirect_uris) = OCTET_LENGTH(_ascii'https://kit.chaoyoufan.cn/oauth2/callback')
    AND HEX(redirect_uris) = HEX(_ascii'https://kit.chaoyoufan.cn/oauth2/callback')
    AND OCTET_LENGTH(scopes) = OCTET_LENGTH(_ascii'openid')
    AND HEX(scopes) = HEX(_ascii'openid')
    AND OCTET_LENGTH(JSON_UNQUOTE(JSON_EXTRACT(client_settings, '$."settings.client.require-proof-key"'))) = OCTET_LENGTH(_ascii'true')
    AND HEX(JSON_UNQUOTE(JSON_EXTRACT(client_settings, '$."settings.client.require-proof-key"'))) = HEX(_ascii'true')
    AND OCTET_LENGTH(JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.access-token-time-to-live"'))) = OCTET_LENGTH(_ascii'PT10M')
    AND HEX(JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.access-token-time-to-live"'))) = HEX(_ascii'PT10M')
    AND OCTET_LENGTH(JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.authorization-code-time-to-live"'))) = OCTET_LENGTH(_ascii'PT5M')
    AND HEX(JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.authorization-code-time-to-live"'))) = HEX(_ascii'PT5M')
);
SET @asf_post_collision_count := (
  SELECT COUNT(*)
  FROM oauth_client
  WHERE client_id = @asf_oauth_client_id
    AND NOT (
      OCTET_LENGTH(client_id) = OCTET_LENGTH(@asf_oauth_client_id)
      AND HEX(client_id) = HEX(@asf_oauth_client_id)
    )
);
SET @asf_guard_sql := IF(
  @asf_postcondition_count = 1 AND @asf_post_collision_count = 0,
  'SELECT ''oauth client migration postcondition passed'' AS account_security_migration',
  'SELECT * FROM account_security_foundation_oauth_client_postcondition_failed'
);
PREPARE asf_guard_stmt FROM @asf_guard_sql;
EXECUTE asf_guard_stmt;
DEALLOCATE PREPARE asf_guard_stmt;

SELECT client_id, client_secret, client_secret_expires_at, client_authentication_methods,
       authorization_grant_types, redirect_uris, scopes,
       JSON_EXTRACT(client_settings, '$."settings.client.require-proof-key"') AS require_proof_key,
       JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.access-token-time-to-live"')) AS access_token_ttl,
       JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.authorization-code-time-to-live"')) AS authorization_code_ttl
FROM oauth_client
WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(@asf_oauth_client_id)
  AND HEX(client_id) = HEX(@asf_oauth_client_id);
