-- Prerequisite: retain the mode-600 preflight capture and its generated byte-exact rollback SQL.
-- The migration operator needs CREATE ROUTINE, ALTER ROUTINE, EXECUTE, SELECT, and UPDATE privileges.
-- The forced PRIMARY-key range scan is intentional: client_id has no proven unique index, so an InnoDB
-- SERIALIZABLE locking read must cover every row and gap before guard counts are trusted.
DROP PROCEDURE IF EXISTS asf_migrate_account_security_oauth_client;
DELIMITER $$
CREATE PROCEDURE asf_migrate_account_security_oauth_client()
SQL SECURITY INVOKER
main: BEGIN
    DECLARE v_locked_table_rows BIGINT DEFAULT 0;
    DECLARE v_innodb_table_count BIGINT DEFAULT 0;
    DECLARE v_exact_target_count BIGINT DEFAULT 0;
    DECLARE v_target_collision_count BIGINT DEFAULT 0;
    DECLARE v_target_invalid_json_count BIGINT DEFAULT 0;
    DECLARE v_updated_rows BIGINT DEFAULT 0;
    DECLARE v_post_exact_target_count BIGINT DEFAULT 0;
    DECLARE v_post_collision_count BIGINT DEFAULT 0;
    DECLARE v_post_invalid_json_count BIGINT DEFAULT 0;
    DECLARE v_postcondition_count BIGINT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    START TRANSACTION;

    -- oauth_client has only PRIMARY(id) in the captured schema. Scanning the complete primary-key
    -- range FOR UPDATE locks all existing rows and gaps, including the supremum gap, until commit.
    SELECT COUNT(*)
      INTO v_locked_table_rows
      FROM oauth_client FORCE INDEX (PRIMARY)
     WHERE id >= _utf8mb4''
       FOR UPDATE;

    -- No write is attempted unless the table is transactional; the preceding table access also holds
    -- its metadata lock so the engine cannot be swapped after this check and before commit.
    SELECT COUNT(*)
      INTO v_innodb_table_count
      FROM information_schema.tables
     WHERE table_schema = DATABASE()
       AND table_name = 'oauth_client'
       AND engine = 'InnoDB';
    IF v_innodb_table_count <> 1 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'account-security-foundation: oauth_client must be InnoDB';
    END IF;

    SELECT COUNT(*)
      INTO v_exact_target_count
      FROM oauth_client
     WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
       AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c');

    SELECT COUNT(*)
      INTO v_target_collision_count
      FROM oauth_client
     WHERE client_id = _ascii'jiafewnnv58ec2379c'
       AND NOT (
           OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
           AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c')
       );

    SELECT COUNT(*)
      INTO v_target_invalid_json_count
      FROM oauth_client
     WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
       AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c')
       AND (client_settings IS NULL OR token_settings IS NULL
            OR NOT JSON_VALID(client_settings) OR NOT JSON_VALID(token_settings));

    IF v_exact_target_count <> 1 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'account-security-foundation: expected one byte-exact oauth client';
    END IF;
    IF v_target_collision_count <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'account-security-foundation: folded or trailing oauth client collision';
    END IF;
    IF v_target_invalid_json_count <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'account-security-foundation: oauth client settings must be valid JSON';
    END IF;

    UPDATE oauth_client
       SET client_secret = NULL,
           client_secret_expires_at = NULL,
           client_authentication_methods = 'none',
           authorization_grant_types = 'authorization_code',
           redirect_uris = 'https://kit.chaoyoufan.cn/oauth2/callback',
           scopes = 'openid',
           client_settings = JSON_SET(client_settings,
               '$."settings.client.require-proof-key"', CAST('true' AS JSON)),
           token_settings = JSON_SET(token_settings,
               '$."settings.token.access-token-time-to-live"', 'PT10M',
               '$."settings.token.authorization-code-time-to-live"', 'PT5M')
     WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
       AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c')
       AND client_settings IS NOT NULL
       AND token_settings IS NOT NULL
       AND JSON_VALID(client_settings)
       AND JSON_VALID(token_settings)
       AND v_exact_target_count = 1
       AND v_target_collision_count = 0
       AND v_target_invalid_json_count = 0;

    SET v_updated_rows = ROW_COUNT();
    IF v_updated_rows <> 1 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'account-security-foundation: oauth client update affected an unexpected row count';
    END IF;

    SELECT COUNT(*)
      INTO v_post_exact_target_count
      FROM oauth_client
     WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
       AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c');

    SELECT COUNT(*)
      INTO v_post_collision_count
      FROM oauth_client
     WHERE client_id = _ascii'jiafewnnv58ec2379c'
       AND NOT (
           OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
           AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c')
       );

    SELECT COUNT(*)
      INTO v_post_invalid_json_count
      FROM oauth_client
     WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
       AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c')
       AND (client_settings IS NULL OR token_settings IS NULL
            OR NOT JSON_VALID(client_settings) OR NOT JSON_VALID(token_settings));

    SELECT COUNT(*)
      INTO v_postcondition_count
      FROM oauth_client
     WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
       AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c')
       AND client_secret IS NULL
       AND client_secret_expires_at IS NULL
       AND OCTET_LENGTH(client_authentication_methods) = OCTET_LENGTH(_ascii'none')
       AND HEX(client_authentication_methods) = HEX(_ascii'none')
       AND OCTET_LENGTH(authorization_grant_types) = OCTET_LENGTH(_ascii'authorization_code')
       AND HEX(authorization_grant_types) = HEX(_ascii'authorization_code')
       AND OCTET_LENGTH(redirect_uris) = OCTET_LENGTH(_ascii'https://kit.chaoyoufan.cn/oauth2/callback')
       AND HEX(redirect_uris) = HEX(_ascii'https://kit.chaoyoufan.cn/oauth2/callback')
       AND OCTET_LENGTH(scopes) = OCTET_LENGTH(_ascii'openid')
       AND HEX(scopes) = HEX(_ascii'openid')
       AND OCTET_LENGTH(JSON_UNQUOTE(JSON_EXTRACT(client_settings, '$."settings.client.require-proof-key"'))) = OCTET_LENGTH(_ascii'true')
       AND HEX(JSON_UNQUOTE(JSON_EXTRACT(client_settings, '$."settings.client.require-proof-key"'))) = HEX(_ascii'true')
       AND OCTET_LENGTH(JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.access-token-time-to-live"'))) = OCTET_LENGTH(_ascii'PT10M')
       AND HEX(JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.access-token-time-to-live"'))) = HEX(_ascii'PT10M')
       AND OCTET_LENGTH(JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.authorization-code-time-to-live"'))) = OCTET_LENGTH(_ascii'PT5M')
       AND HEX(JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.authorization-code-time-to-live"'))) = HEX(_ascii'PT5M');

    IF v_post_exact_target_count <> 1
       OR v_post_collision_count <> 0
       OR v_post_invalid_json_count <> 0
       OR v_postcondition_count <> 1 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'account-security-foundation: oauth client postcondition failed';
    END IF;

    COMMIT;
    SELECT v_updated_rows AS migrated_target_client_rows,
           v_postcondition_count AS verified_target_client_rows;
END$$
DELIMITER ;

CALL asf_migrate_account_security_oauth_client();
DROP PROCEDURE asf_migrate_account_security_oauth_client;

SELECT client_id, client_secret, client_secret_expires_at, client_authentication_methods,
       authorization_grant_types, redirect_uris, scopes,
       JSON_EXTRACT(client_settings, '$."settings.client.require-proof-key"') AS require_proof_key,
       JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.access-token-time-to-live"')) AS access_token_ttl,
       JSON_UNQUOTE(JSON_EXTRACT(token_settings, '$."settings.token.authorization-code-time-to-live"')) AS authorization_code_ttl
FROM oauth_client
WHERE OCTET_LENGTH(client_id) = OCTET_LENGTH(_ascii'jiafewnnv58ec2379c')
  AND HEX(client_id) = HEX(_ascii'jiafewnnv58ec2379c');
