CREATE TABLE IF NOT EXISTS archive_collection (
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    revision BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (collection_id),
    UNIQUE KEY uk_archive_collection_code (code),
    CONSTRAINT chk_archive_collection_revision CHECK (revision >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_collection_manager (
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    permissions VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    revision BIGINT NOT NULL,
    revoked_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (collection_id, tenant_id, client_id, owner_jiacn),
    CONSTRAINT fk_archive_manager_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT chk_archive_manager_state CHECK (state IN ('ACTIVE','REVOKED')),
    CONSTRAINT chk_archive_manager_revision CHECK (revision >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_collection_work (
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    work_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    canonical_key VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    revision BIGINT NOT NULL,
    PRIMARY KEY (collection_id, work_id),
    UNIQUE KEY uk_archive_collection_canonical (collection_id, canonical_key),
    KEY fk_archive_collection_work_work (work_id),
    CONSTRAINT fk_archive_collection_work_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT fk_archive_collection_work_work FOREIGN KEY (work_id) REFERENCES archive_work(work_id),
    CONSTRAINT chk_archive_collection_work_revision CHECK (revision >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_appointment_slot (
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    role_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    current_appointment_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    revision BIGINT NOT NULL,
    PRIMARY KEY (collection_id, role_code),
    CONSTRAINT fk_archive_slot_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT chk_archive_slot_revision CHECK (revision >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_appointment (
    appointment_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    role_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    agent_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    binding_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    work_scope_mode VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    work_ids TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    permission_profile VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    required_skill_key VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    required_skill_version VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    required_skill_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    revision BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    revoked_at TIMESTAMP(6) NULL,
    PRIMARY KEY (appointment_id),
    KEY idx_archive_appointment_slot (collection_id, role_code, created_at),
    CONSTRAINT fk_archive_appointment_slot FOREIGN KEY (collection_id, role_code) REFERENCES archive_appointment_slot(collection_id, role_code),
    CONSTRAINT chk_archive_appointment_state CHECK (status IN ('ACTIVE','REVOKED')),
    CONSTRAINT chk_archive_appointment_profile CHECK (permission_profile IN ('DRAFT_ONLY','PUBLISH_VALIDATED')),
    CONSTRAINT chk_archive_appointment_scope CHECK (work_scope_mode IN ('COLLECTION','EXPLICIT_WORKS')),
    CONSTRAINT chk_archive_appointment_revision CHECK (revision >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_source_snapshot (
    source_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    storage_uri VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    raw_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    raw_byte_length BIGINT NOT NULL,
    source_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    source_version VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    rights_basis VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    normalization_rule VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (source_id),
    KEY idx_archive_source_collection (collection_id, created_at),
    CONSTRAINT fk_archive_source_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT chk_archive_source_length CHECK (raw_byte_length > 0),
    CONSTRAINT chk_archive_source_state CHECK (state = 'READY')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
CREATE TABLE IF NOT EXISTS archive_confirmed_request (
    confirmation_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_intent_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    request_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    publication_mode_ceiling VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    conversation_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    canonical_message_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    conversation_generation BIGINT NULL,
    turn_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    entry_point VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
    target_agent_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    revision BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    bound_at TIMESTAMP(6) NULL,
    PRIMARY KEY (confirmation_ref),
    UNIQUE KEY uk_archive_confirmation_intent (tenant_id, client_id, owner_jiacn, request_intent_id),
    KEY fk_archive_confirmation_collection (collection_id),
    CONSTRAINT fk_archive_confirmation_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT chk_archive_confirmation_mode CHECK (publication_mode_ceiling IN ('MANUAL','AUTO')),
    CONSTRAINT chk_archive_confirmation_revision CHECK (revision >= 1),
    CONSTRAINT chk_archive_confirmation_binding CHECK (((conversation_id IS NULL) AND (canonical_message_id IS NULL) AND (conversation_generation IS NULL) AND (turn_sha256 IS NULL) AND (entry_point IS NULL) AND (target_agent_id IS NULL)) OR ((conversation_id IS NOT NULL) AND (canonical_message_id IS NOT NULL) AND (conversation_generation >= 1) AND (turn_sha256 IS NOT NULL) AND (((entry_point='SONGJIANG') AND (target_agent_id IS NULL)) OR ((entry_point='DIRECT_PRIVATE') AND (target_agent_id IS NOT NULL)))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_maintenance_job (
    job_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    run_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    target_agent_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    appointment_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    appointment_revision BIGINT NULL,
    agent_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    binding_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    permission_profile VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    manager_authorization_revision BIGINT NOT NULL,
    publication_mode VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    work_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    canonical_key VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    title VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    source_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_summary VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    rights_basis VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    wait_reason VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    revision BIGINT NOT NULL,
    draft_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    publication_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    request_intent_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (job_id),
    UNIQUE KEY uk_archive_job_run (run_id),
    UNIQUE KEY uk_archive_job_intent (tenant_id, client_id, owner_jiacn, request_intent_id),
    KEY idx_archive_job_collection (collection_id, updated_at, job_id),
    KEY fk_archive_job_appointment (appointment_id),
    KEY fk_archive_job_source (source_id),
    CONSTRAINT fk_archive_job_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT fk_archive_job_appointment FOREIGN KEY (appointment_id) REFERENCES archive_appointment(appointment_id),
    CONSTRAINT fk_archive_job_source FOREIGN KEY (source_id) REFERENCES archive_source_snapshot(source_id),
    CONSTRAINT chk_archive_job_mode CHECK (publication_mode IN ('MANUAL','AUTO')),
    CONSTRAINT chk_archive_job_state CHECK (state IN ('WAITING_INPUT','WAITING_ASSIGNEE','WAITING_SKILL','EXECUTION_REQUESTED','RUNNING','NEEDS_CHANGES','AWAITING_PUBLISH','PUBLISHING','PUBLISHED','SUSPENDED_AUTH','FAILED','CANCELLED')),
    CONSTRAINT chk_archive_job_revision CHECK ((revision >= 1) AND (manager_authorization_revision >= 1)),
    CONSTRAINT chk_archive_job_assignment CHECK (((appointment_id IS NULL) AND (appointment_revision IS NULL) AND (agent_id IS NULL) AND (binding_version IS NULL) AND (permission_profile IS NULL)) OR ((appointment_id IS NOT NULL) AND (appointment_revision >= 1) AND (agent_id IS NOT NULL) AND (binding_version IS NOT NULL) AND (permission_profile IN ('DRAFT_ONLY','PUBLISH_VALIDATED')))),
    CONSTRAINT chk_archive_job_source_shape CHECK (((source_id IS NULL) AND (source_sha256 IS NULL) AND (source_summary IS NULL) AND (rights_basis IS NULL)) OR ((source_id IS NOT NULL) AND (source_sha256 IS NOT NULL) AND (source_summary IS NOT NULL) AND (rights_basis IS NOT NULL))),
    CONSTRAINT chk_archive_job_work_shape CHECK (((work_id IS NULL) AND (canonical_key IS NULL) AND (title IS NULL)) OR ((work_id IS NOT NULL) AND (canonical_key IS NOT NULL) AND (title IS NOT NULL))),
    CONSTRAINT chk_archive_job_candidate_shape CHECK (((run_id IS NULL) AND (draft_id IS NULL)) OR ((run_id IS NOT NULL) AND (draft_id IS NOT NULL))),
    CONSTRAINT chk_archive_job_waiting_shape CHECK (((state='WAITING_INPUT') AND (run_id IS NULL) AND (draft_id IS NULL) AND (appointment_id IS NULL) AND (publication_id IS NULL) AND ((source_id IS NULL) OR (work_id IS NULL))) OR ((state='WAITING_ASSIGNEE') AND (run_id IS NULL) AND (draft_id IS NULL) AND (appointment_id IS NULL) AND (source_id IS NOT NULL) AND (work_id IS NOT NULL) AND (publication_id IS NULL)) OR ((state='CANCELLED') AND (publication_id IS NULL) AND (((run_id IS NULL) AND (draft_id IS NULL) AND (appointment_id IS NULL)) OR ((run_id IS NOT NULL) AND (draft_id IS NOT NULL) AND (appointment_id IS NOT NULL) AND (source_id IS NOT NULL) AND (work_id IS NOT NULL)))) OR ((state NOT IN ('WAITING_INPUT','WAITING_ASSIGNEE','CANCELLED')) AND (run_id IS NOT NULL) AND (draft_id IS NOT NULL) AND (appointment_id IS NOT NULL) AND (source_id IS NOT NULL) AND (work_id IS NOT NULL)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_job_run (
    run_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    job_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    execution_epoch BIGINT NOT NULL,
    runtime_instance_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    grant_revision BIGINT NOT NULL,
    started_message_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    failure_phase VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    failure_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    failure_retryable BIGINT NULL,
    state VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    revision BIGINT NOT NULL,
    PRIMARY KEY (run_id),
    UNIQUE KEY uk_archive_job_current_run (job_id, run_id),
    CONSTRAINT fk_archive_run_job FOREIGN KEY (job_id) REFERENCES archive_maintenance_job(job_id),
    CONSTRAINT chk_archive_run_revision CHECK ((revision >= 1) AND (grant_revision >= 1) AND (execution_epoch >= 1)),
    CONSTRAINT chk_archive_run_state CHECK (state IN ('WAITING','AUTHORIZED','RUNNING','COMPLETED','FAILED','FENCED')),
    CONSTRAINT chk_archive_run_failure_retryable CHECK ((failure_retryable IS NULL) OR (failure_retryable IN (0,1))),

    CONSTRAINT chk_archive_run_lifecycle CHECK (((state IN ('WAITING','AUTHORIZED')) AND (started_message_id IS NULL) AND (failure_phase IS NULL) AND (failure_code IS NULL) AND (failure_retryable IS NULL)) OR ((state IN ('RUNNING','COMPLETED')) AND (started_message_id IS NOT NULL) AND (failure_phase IS NULL) AND (failure_code IS NULL) AND (failure_retryable IS NULL)) OR ((state='FAILED') AND (started_message_id IS NOT NULL) AND (failure_phase IS NOT NULL) AND (failure_code IS NOT NULL) AND (failure_retryable IS NOT NULL)) OR (state='FENCED'))

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_execution_grant (
    grant_ref VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    run_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    appointment_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    appointment_revision BIGINT NOT NULL,
    manager_authorization_revision BIGINT NOT NULL,
    agent_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    binding_version BIGINT NOT NULL,
    execution_ref VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    command_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    active_attempt BIGINT NOT NULL,
    execution_epoch BIGINT NOT NULL,
    runtime_instance_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    registration_hash BINARY(32) NOT NULL,
    skill_origin VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    installation_ref VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    installation_revision BIGINT NOT NULL,
    skill_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    skill_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    package_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    dispatch_key VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    context_ref VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    expires_at BIGINT NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    revision BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (grant_ref),
    UNIQUE KEY uk_archive_execution_run (run_id),
    UNIQUE KEY uk_archive_execution_ref (execution_ref),
    UNIQUE KEY uk_archive_execution_command (tenant_id, client_id, owner_jiacn, command_id),
    UNIQUE KEY uk_archive_execution_dispatch (tenant_id, client_id, owner_jiacn, dispatch_key),
    KEY idx_archive_execution_appointment (appointment_id, state, run_id),
    CONSTRAINT fk_archive_execution_run FOREIGN KEY (run_id) REFERENCES archive_job_run(run_id),
    CONSTRAINT fk_archive_execution_appointment FOREIGN KEY (appointment_id) REFERENCES archive_appointment(appointment_id),
    CONSTRAINT chk_archive_execution_state CHECK (state IN ('ACTIVE','READ_ONLY','FENCED')),
    CONSTRAINT chk_archive_execution_versions CHECK ((appointment_revision >= 1) AND (manager_authorization_revision >= 1) AND (binding_version >= 1) AND (active_attempt >= 1) AND (execution_epoch >= 1) AND (installation_revision >= 1) AND (revision >= 1)),
    CONSTRAINT chk_archive_execution_origin CHECK (skill_origin IN ('PLATFORM_PROVISIONED','MARKET')),
    CONSTRAINT chk_archive_execution_expiry CHECK (expires_at > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_draft (
    draft_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    job_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    revision BIGINT NOT NULL,
    state VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    content_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    validated_revision BIGINT NULL,
    validation_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (draft_id),
    UNIQUE KEY uk_archive_draft_job (job_id),
    CONSTRAINT fk_archive_draft_job FOREIGN KEY (job_id) REFERENCES archive_maintenance_job(job_id),
    CONSTRAINT chk_archive_draft_revision CHECK (revision >= 0),
    CONSTRAINT chk_archive_draft_state CHECK (state IN ('EDITABLE','VALIDATED','SEALED','CHANGES_REQUIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_validation (
    validation_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    draft_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    draft_revision BIGINT NOT NULL,
    outcome VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    validation_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    findings_json TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (validation_id),
    UNIQUE KEY uk_archive_validation_candidate (draft_id, draft_revision, validation_digest),
    CONSTRAINT fk_archive_validation_draft FOREIGN KEY (draft_id) REFERENCES archive_draft(draft_id),
    CONSTRAINT chk_archive_validation_outcome CHECK (outcome IN ('PASSED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_publication (
    publication_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    job_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    work_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    edition_id VARCHAR(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    draft_revision BIGINT NOT NULL,
    manifest_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    actor_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    actor_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    authorization_revision BIGINT NOT NULL,
    published_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (publication_id),
    UNIQUE KEY uk_archive_publication_edition (edition_id),
    UNIQUE KEY uk_archive_publication_job (job_id),
    KEY idx_archive_publication_work (work_id, state, published_at),
    KEY fk_archive_publication_collection (collection_id),
    CONSTRAINT fk_archive_publication_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT fk_archive_publication_work FOREIGN KEY (work_id) REFERENCES archive_work(work_id),
    CONSTRAINT fk_archive_publication_edition FOREIGN KEY (edition_id) REFERENCES archive_edition(edition_id),
    CONSTRAINT chk_archive_publication_state CHECK (state IN ('PUBLISHED','WITHDRAWN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_publication_readback (
    publication_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    revision BIGINT NOT NULL,
    verification_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    findings_json TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    checked_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (publication_id),
    CONSTRAINT fk_archive_readback_publication FOREIGN KEY (publication_id) REFERENCES archive_publication(publication_id),
    CONSTRAINT chk_archive_readback_revision CHECK (revision >= 1),
    CONSTRAINT chk_archive_readback_state CHECK (((state='PENDING') AND (verification_digest IS NULL) AND (checked_at IS NULL)) OR ((state IN ('PASSED','FAILED')) AND (verification_digest IS NOT NULL) AND (checked_at IS NOT NULL)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_edition_withdrawal (
    withdrawal_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    publication_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    work_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    edition_id VARCHAR(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    reason VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    actor_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    actor_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    authorization_revision BIGINT NOT NULL,
    requested_replacement_active_edition_id VARCHAR(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    resulting_active_edition_id VARCHAR(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    resulting_work_revision BIGINT NOT NULL,
    operation_key VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    withdrawn_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    outbox_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (withdrawal_id),
    UNIQUE KEY uk_archive_withdrawal_publication (publication_id),
    UNIQUE KEY uk_archive_withdrawal_operation (tenant_id, client_id, owner_jiacn, operation_key),
    KEY idx_archive_withdrawal_work (work_id, withdrawn_at),
    KEY fk_archive_withdrawal_collection (collection_id),
    KEY fk_archive_withdrawal_edition (edition_id),
    CONSTRAINT fk_archive_withdrawal_publication FOREIGN KEY (publication_id) REFERENCES archive_publication(publication_id),
    CONSTRAINT fk_archive_withdrawal_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT fk_archive_withdrawal_work FOREIGN KEY (work_id) REFERENCES archive_work(work_id),
    CONSTRAINT fk_archive_withdrawal_edition FOREIGN KEY (edition_id) REFERENCES archive_edition(edition_id),
    CONSTRAINT chk_archive_withdrawal_revision CHECK ((authorization_revision >= 1) AND (resulting_work_revision >= 1)),
    CONSTRAINT chk_archive_withdrawal_actor CHECK (actor_type = 'HUMAN'),
    CONSTRAINT chk_archive_withdrawal_outbox CHECK (outbox_state IN ('PENDING','DELIVERED','NO_TARGET'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
CREATE TABLE IF NOT EXISTS archive_event (
    job_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    sequence BIGINT NOT NULL,
    schema_version BIGINT NOT NULL,
    event_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    job_revision BIGINT NOT NULL,
    data_json TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    outbox_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (job_id, sequence),
    KEY idx_archive_event_outbox (outbox_state, occurred_at),
    CONSTRAINT fk_archive_event_job FOREIGN KEY (job_id) REFERENCES archive_maintenance_job(job_id),
    CONSTRAINT chk_archive_event_sequence CHECK ((sequence >= 1) AND (schema_version >= 1) AND (job_revision >= 1)),
    CONSTRAINT chk_archive_event_outbox CHECK (outbox_state IN ('PENDING','DELIVERED','NO_TARGET'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
CREATE TABLE IF NOT EXISTS archive_business_outbox (
    projection_key VARCHAR(180) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    job_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    event_sequence BIGINT NULL,
    withdrawal_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    state VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    attempt_count BIGINT NOT NULL,
    fencing_token BIGINT NOT NULL,
    available_at TIMESTAMP(6) NOT NULL,
    lease_until TIMESTAMP(6) NULL,
    last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    projected_message_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (projection_key),
    UNIQUE KEY uk_archive_business_event (job_id,event_sequence),
    UNIQUE KEY uk_archive_business_withdrawal (withdrawal_id),
    KEY idx_archive_business_available (state,available_at,projection_key),
    KEY idx_archive_business_lease (state,lease_until,projection_key),
    CONSTRAINT fk_archive_business_job FOREIGN KEY (job_id) REFERENCES archive_maintenance_job(job_id),
    CONSTRAINT fk_archive_business_event FOREIGN KEY (job_id,event_sequence) REFERENCES archive_event(job_id,sequence),
    CONSTRAINT fk_archive_business_withdrawal FOREIGN KEY (withdrawal_id) REFERENCES archive_edition_withdrawal(withdrawal_id),
    CONSTRAINT chk_archive_business_source CHECK (((source_type='JOB_EVENT') AND (event_sequence IS NOT NULL) AND (event_sequence >= 1) AND (withdrawal_id IS NULL)) OR ((source_type='WITHDRAWAL') AND (event_sequence IS NULL) AND (withdrawal_id IS NOT NULL))),
    CONSTRAINT chk_archive_business_state CHECK (state IN ('READY','LEASED','WAITING_RETRY','DELIVERED','NO_TARGET')),
    CONSTRAINT chk_archive_business_counters CHECK ((attempt_count >= 0) AND (fencing_token >= 0)),
    CONSTRAINT chk_archive_business_lease CHECK (((state='LEASED') AND (lease_until IS NOT NULL)) OR ((state IN ('READY','WAITING_RETRY','DELIVERED','NO_TARGET')) AND (lease_until IS NULL))),
    CONSTRAINT chk_archive_business_result CHECK (((state='DELIVERED') AND (projected_message_id IS NOT NULL)) OR ((state<>'DELIVERED') AND (projected_message_id IS NULL))),
    CONSTRAINT chk_archive_business_error CHECK (((state IN ('READY','LEASED','DELIVERED')) AND (last_error_code IS NULL)) OR ((state IN ('WAITING_RETRY','NO_TARGET')) AND (last_error_code IS NOT NULL)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
CREATE TABLE IF NOT EXISTS archive_operation (
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    operation_key VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    http_method VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    canonical_path VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    target_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    target_id VARCHAR(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, client_id, owner_jiacn, operation_key),
    CONSTRAINT chk_archive_operation_state CHECK (state IN ('PENDING','COMMITTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS archive_admin_operation_receipt (
    operation_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    client_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    owner_jiacn VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    operation_key VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    collection_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    job_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    draft_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    action VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    authorization_revision BIGINT NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    result_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    committed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (operation_id),
    UNIQUE KEY uk_archive_admin_operation_key (tenant_id,client_id,owner_jiacn,operation_key),
    KEY fk_archive_admin_operation_collection (collection_id),
    KEY fk_archive_admin_operation_job (job_id),
    KEY fk_archive_admin_operation_draft (draft_id),
    CONSTRAINT fk_archive_admin_operation_key FOREIGN KEY (tenant_id,client_id,owner_jiacn,operation_key) REFERENCES archive_operation(tenant_id,client_id,owner_jiacn,operation_key),
    CONSTRAINT fk_archive_admin_operation_collection FOREIGN KEY (collection_id) REFERENCES archive_collection(collection_id),
    CONSTRAINT fk_archive_admin_operation_job FOREIGN KEY (job_id) REFERENCES archive_maintenance_job(job_id),
    CONSTRAINT fk_archive_admin_operation_draft FOREIGN KEY (draft_id) REFERENCES archive_draft(draft_id),
    CONSTRAINT chk_archive_admin_operation_revision CHECK (authorization_revision >= 1),
    CONSTRAINT chk_archive_admin_operation_action CHECK (action IN ('BLOCK_PUT','DRAFT_PATCH','DRAFT_VALIDATE','DRAFT_PUBLISH')),
    CONSTRAINT chk_archive_admin_operation_state CHECK (((state='PENDING') AND (result_json IS NULL) AND (committed_at IS NULL)) OR ((state='COMMITTED') AND (result_json IS NOT NULL) AND (committed_at IS NOT NULL)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
INSERT IGNORE INTO archive_collection(collection_id, code, revision)
VALUES ('platform-classics', 'platform-classics', 1);
