dependencies {
	api project(':common:jia-common-core')
	implementation project(':common:jia-common-service')
	api project(':chat:jia-chat-api')
	implementation project(':chat:jia-chat-mapper')
	implementation project(':agent:jia-agent-api')
	implementation project(':agent:jia-agent-service')
	compileOnly project(':oauth:jia-oauth-api')
	implementation project(':task:jia-task-core')
    implementation project(':task:jia-task-api')
	compileOnly project(':point:jia-point-api')
	compileOnly project(':kefu:jia-kefu-api')
	compileOnly project(':material:jia-material-api')
	implementation libs.spring.boot.starter.webflux
	implementation libs.spring.ai.starter.mcp.client
	compileOnly libs.spring.ai.starter.model.deepseek
	compileOnly "org.springframework.ai:spring-ai-starter-model-openai:${libs.versions.spring.ai.asProvider().get()}"
	compileOnly libs.spring.ai.starter.model.ollama
	compileOnly(libs.spring.boot.starter.elasticsearch)
//	implementation libs.spring.ai.starter.vector.store.elasticsearch
	// implementation 'org.springframework.ai:spring-ai-starter-vector-store-redis'
	compileOnly libs.spring.ai.vector.store.advisor
	implementation libs.spring.ai.starter.tool.search.advisor
	implementation libs.spring.ai.agent.utils
	compileOnly libs.spring.boot.starter.websocket
	compileOnly libs.spring.security.oauth2.client
	compileOnly 'org.springframework.security:spring-security-oauth2-resource-server'
	compileOnly 'org.springframework.security:spring-security-oauth2-jose'
	testImplementation 'org.springframework.security:spring-security-oauth2-resource-server'
	testImplementation 'org.springframework.security:spring-security-oauth2-jose'
//	implementation 'org.springframework.retry:spring-retry'
//	implementation 'org.springframework:spring-aspects'
	testImplementation project(':common:jia-common-test')
	testImplementation project(':agent:jia-agent-mapper')
	testImplementation libs.spring.ai.starter.mcp.client
	testImplementation "org.springframework.ai:spring-ai-starter-model-openai:${libs.versions.spring.ai.asProvider().get()}"
	testImplementation libs.spring.boot.starter.websocket
}

version = '1.1.2-SNAPSHOT'
description = 'jia-chat-service'
