package cn.jia.chat.archive.maintenance.service;

import cn.jia.chat.archive.maintenance.dto.ArchiveDraftUpdateRequest;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/** Golden vectors generated by the approved package's pure plain-text-v1 adapter. */
class ArchiveSourceMappingGoldenVectorTest {
    private static final String ROOT = "/platform-skills/archive-maintainer/fixtures/";
    private final ObjectMapper mapper = new ObjectMapper();

    @Test void packageVectorsRemainExactAcrossJavaValidationAndCanonicalJson() throws Exception {
        for (String name : List.of("ordinary-crlf-bom-emoji", "no-preface-multichapter", "malicious-instructions")) {
            byte[] source = resource(name + ".txt");
            JsonNode vector = mapper.readTree(resource(name + ".expected.json"));
            ArchiveDraftUpdateRequest draft = mapper.treeToValue(vector.path("draft"), ArchiveDraftUpdateRequest.class);
            assertEquals(vector.path("sourceSha256").asText(), sha256(source), name);
            assertEquals(vector.path("canonicalJsonSha256").asText(), sha256(canonical(vector.path("draft"))), name);
            assertTrue(ArchiveSourceMappingValidator.validate(source, draft).isEmpty(), name);
        }
    }

    @Test void rangeAndTextTamperingFailAgainstTheSameSourceVector() throws Exception {
        byte[] source = resource("ordinary-crlf-bom-emoji.txt");
        JsonNode rangeTamper = mapper.readTree(resource("invalid-tampered-range.json"));
        assertFalse(ArchiveSourceMappingValidator.validate(source,
                mapper.treeToValue(rangeTamper.path("draft"), ArchiveDraftUpdateRequest.class)).isEmpty());
        JsonNode textTamper = mapper.readTree(resource("ordinary-crlf-bom-emoji.expected.json"));
        ((com.fasterxml.jackson.databind.node.ObjectNode) textTamper.path("draft").path("blocks").get(1)
                .path("paragraphs").get(0)).put("text", "编造");
        assertTrue(ArchiveSourceMappingValidator.validate(source,
                mapper.treeToValue(textTamper.path("draft"), ArchiveDraftUpdateRequest.class)).stream()
                .anyMatch(finding -> finding.contains("does not match")));
    }

    private byte[] resource(String name) throws Exception {
        try (InputStream input = getClass().getResourceAsStream(ROOT + name)) {
            assertNotNull(input, name);
            return input.readAllBytes();
        }
    }

    private static String sha256(byte[] bytes) throws Exception {
        return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
    }

    private byte[] canonical(JsonNode node) throws Exception {
        StringBuilder output = new StringBuilder();
        append(node, output);
        return output.toString().getBytes(StandardCharsets.UTF_8);
    }

    private void append(JsonNode node, StringBuilder output) throws Exception {
        if (node.isObject()) {
            List<String> names = new ArrayList<>();
            node.fieldNames().forEachRemaining(names::add);
            names.sort(ArchiveSourceMappingGoldenVectorTest::compareCodePoints);
            output.append('{');
            for (int index = 0; index < names.size(); index++) {
                if (index > 0) output.append(',');
                String name = names.get(index);
                output.append(mapper.writeValueAsString(name)).append(':');
                append(node.get(name), output);
            }
            output.append('}');
        } else if (node.isArray()) {
            output.append('[');
            for (int index = 0; index < node.size(); index++) {
                if (index > 0) output.append(',');
                append(node.get(index), output);
            }
            output.append(']');
        } else if (node.isTextual()) output.append(mapper.writeValueAsString(node.textValue()));
        else if (node.isIntegralNumber() || node.isBoolean() || node.isNull()) output.append(node.toString());
        else fail("canonical-json-v1 permits no floating point values");
    }

    private static int compareCodePoints(String left, String right) {
        int[] a = left.codePoints().toArray();
        int[] b = right.codePoints().toArray();
        for (int index = 0; index < Math.min(a.length, b.length); index++) {
            int compare = Integer.compare(a[index], b[index]);
            if (compare != 0) return compare;
        }
        return Integer.compare(a.length, b.length);
    }
}