-- W06 immutable successful preview settlement only. Held/refunded remain W04 funding projections.
CREATE TABLE IF NOT EXISTS agent_task_bounty_settlement (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  principal_type VARCHAR(20) NOT NULL,
  principal_id VARCHAR(100) NOT NULL,
  idempotency_key VARBINARY(36) NOT NULL,
  request_hash BINARY(32) NOT NULL,
  task_id VARCHAR(100) NOT NULL,
  quote_id VARCHAR(100) NOT NULL,
  agent_id VARCHAR(100) NOT NULL,
  escrow_id VARCHAR(100) NOT NULL,
  status VARCHAR(16) NOT NULL,
  gross_micro BIGINT NOT NULL,
  actual_compute_micro BIGINT NOT NULL,
  platform_fee_micro BIGINT NOT NULL,
  agent_payout_micro BIGINT NOT NULL,
  refunded_micro BIGINT NOT NULL,
  task_version BIGINT NOT NULL,
  funding_version BIGINT NOT NULL,
  escrow_version BIGINT NOT NULL,
  settled_at BIGINT NOT NULL,
  transaction_ids TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_bounty_settlement_task (tenant_id,client_id,task_id),
  UNIQUE KEY uk_bounty_settlement_actor_key (tenant_id,client_id,principal_type,principal_id,idempotency_key),
  CONSTRAINT chk_bounty_settlement_identity CHECK (principal_type='USER' AND OCTET_LENGTH(idempotency_key)=36 AND OCTET_LENGTH(request_hash)=32),
  CONSTRAINT chk_bounty_settlement_state CHECK (status='SETTLED' AND task_version>0 AND funding_version>=2 AND escrow_version>1 AND settled_at>0 AND OCTET_LENGTH(transaction_ids)>2),
  CONSTRAINT chk_bounty_settlement_amount CHECK (gross_micro>0 AND actual_compute_micro>=0 AND platform_fee_micro>=0 AND agent_payout_micro>=0 AND refunded_micro=0 AND gross_micro=actual_compute_micro + platform_fee_micro + agent_payout_micro)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
