-- 1.11 C1-C/D private execution grants. No public task/bounty rows are created.
CREATE TABLE IF NOT EXISTS agent_personal_workspace_execution (
  id BIGINT NOT NULL AUTO_INCREMENT,
  execution_id VARCHAR(100) NOT NULL,
  owner_jiacn VARCHAR(50) NOT NULL,
  task_id VARCHAR(100) NOT NULL,
  run_id VARCHAR(100) NOT NULL,
  conversation_id VARCHAR(100) DEFAULT NULL,
  target_agent_id VARCHAR(100) NOT NULL,
  instruction TEXT NOT NULL,
  execution_state VARCHAR(24) NOT NULL,
  grant_revision BIGINT NOT NULL,
  idempotency_key VARCHAR(100) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  revoke_idempotency_key VARCHAR(100) DEFAULT NULL,
  revoke_request_hash CHAR(64) DEFAULT NULL,
  created_at BIGINT NOT NULL,
  revoked_at BIGINT DEFAULT NULL,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  create_time BIGINT DEFAULT NULL,
  update_time BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pwex_execution_scope (tenant_id, client_id, owner_jiacn, execution_id),
  UNIQUE KEY uk_pwex_task_run_scope (tenant_id, client_id, owner_jiacn, task_id, run_id),
  UNIQUE KEY uk_pwex_idempotency_scope (tenant_id, client_id, owner_jiacn, idempotency_key),
  UNIQUE KEY uk_pwex_revoke_idempotency_scope (tenant_id, client_id, owner_jiacn, revoke_idempotency_key),
  KEY idx_pwex_owner_state (tenant_id, client_id, owner_jiacn, execution_state, created_at),
  CONSTRAINT chk_pwex_tenant CHECK (tenant_id = '0'),
  CONSTRAINT chk_pwex_grant_revision CHECK (grant_revision >= 1),
  CONSTRAINT chk_pwex_state CHECK (execution_state IN ('QUEUED','INPUTS_REVOKED','OUTPUT_COMMITTED')),
  CONSTRAINT chk_pwex_hash CHECK (CHAR_LENGTH(request_hash)=64),
  CONSTRAINT chk_pwex_revoke_hash CHECK ((revoke_idempotency_key IS NULL AND revoke_request_hash IS NULL) OR (revoke_idempotency_key IS NOT NULL AND CHAR_LENGTH(revoke_request_hash)=64))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS agent_personal_workspace_execution_input (
  id BIGINT NOT NULL AUTO_INCREMENT,
  input_ref VARCHAR(100) NOT NULL,
  execution_id VARCHAR(100) NOT NULL,
  owner_jiacn VARCHAR(50) NOT NULL,
  file_id VARCHAR(100) NOT NULL,
  file_version INT NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  content_mime_type VARCHAR(127) NOT NULL,
  byte_length BIGINT NOT NULL,
  content_hash CHAR(64) NOT NULL,
  storage_uri VARCHAR(1000) NOT NULL,
  grant_state VARCHAR(24) NOT NULL,
  created_at BIGINT NOT NULL,
  revoked_at BIGINT DEFAULT NULL,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  create_time BIGINT DEFAULT NULL,
  update_time BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pwexi_ref_scope (tenant_id, client_id, owner_jiacn, execution_id, input_ref),
  UNIQUE KEY uk_pwexi_file_version_scope (tenant_id, client_id, owner_jiacn, execution_id, file_id, file_version),
  KEY idx_pwexi_file_active (tenant_id, client_id, owner_jiacn, file_id, grant_state, execution_id),
  CONSTRAINT chk_pwexi_tenant CHECK (tenant_id = '0'),
  CONSTRAINT chk_pwexi_version CHECK (file_version >= 1 AND byte_length >= 0),
  CONSTRAINT chk_pwexi_state CHECK (grant_state IN ('ACTIVE','REVOKED')),
  CONSTRAINT chk_pwexi_hash CHECK (CHAR_LENGTH(content_hash)=64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS agent_personal_workspace_execution_output (
  id BIGINT NOT NULL AUTO_INCREMENT,
  output_id VARCHAR(100) NOT NULL,
  execution_id VARCHAR(100) NOT NULL,
  owner_jiacn VARCHAR(50) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  content_mime_type VARCHAR(127) NOT NULL,
  byte_length BIGINT NOT NULL,
  content_hash CHAR(64) NOT NULL,
  storage_uri VARCHAR(1000) NOT NULL,
  output_state VARCHAR(24) NOT NULL,
  workspace_file_id VARCHAR(100) DEFAULT NULL,
  workspace_file_version INT DEFAULT NULL,
  staged_at BIGINT NOT NULL,
  committed_at BIGINT DEFAULT NULL,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  create_time BIGINT DEFAULT NULL,
  update_time BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pwexo_output_scope (tenant_id, client_id, owner_jiacn, execution_id, output_id),
  KEY idx_pwexo_execution_state (tenant_id, client_id, owner_jiacn, execution_id, output_state),
  CONSTRAINT chk_pwexo_tenant CHECK (tenant_id = '0'),
  CONSTRAINT chk_pwexo_lengths CHECK (byte_length >= 0),
  CONSTRAINT chk_pwexo_state CHECK (output_state IN ('STAGED','COMMITTED')),
  CONSTRAINT chk_pwexo_hash CHECK (CHAR_LENGTH(content_hash)=64),
  CONSTRAINT chk_pwexo_commit CHECK ((output_state='STAGED' AND workspace_file_id IS NULL AND workspace_file_version IS NULL AND committed_at IS NULL) OR (output_state='COMMITTED' AND workspace_file_id IS NOT NULL AND workspace_file_version=1 AND committed_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
