-- D02 additive Protocol v1 report receipt schema. No backfill, Rabbit operation, or production DML.
CREATE TABLE IF NOT EXISTS agent_execution_report_head (
  id BIGINT NOT NULL AUTO_INCREMENT,
  owner_jiacn VARCHAR(50) NOT NULL,
  agent_id VARCHAR(100) NOT NULL,
  runtime_instance_id VARCHAR(100) NOT NULL,
  execution_ref VARCHAR(100) NOT NULL,
  command_id VARCHAR(100) NOT NULL,
  attempt INT NOT NULL,
  last_sequence BIGINT NOT NULL DEFAULT 0,
  committed_version BIGINT NOT NULL DEFAULT 0,
  terminal_report_id VARCHAR(100) DEFAULT NULL,
  terminal_result_ref VARCHAR(100) DEFAULT NULL,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  create_time BIGINT NOT NULL,
  update_time BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_execution_report_head (tenant_id,client_id,owner_jiacn,agent_id,command_id,attempt),
  KEY idx_execution_report_head_execution (tenant_id,client_id,owner_jiacn,execution_ref,agent_id),
  CONSTRAINT chk_execution_report_head_tenant CHECK (tenant_id='0'),
  CONSTRAINT chk_execution_report_head_numbers CHECK (attempt>0 AND last_sequence>=0 AND committed_version>=0),
  CONSTRAINT chk_execution_report_head_terminal CHECK ((terminal_report_id IS NULL AND terminal_result_ref IS NULL) OR (terminal_report_id IS NOT NULL AND terminal_result_ref IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin
  COMMENT='Owner and Agent scoped serialization head for Protocol v1 reports';

CREATE TABLE IF NOT EXISTS agent_execution_report_inbox (
  id BIGINT NOT NULL AUTO_INCREMENT,
  report_id VARCHAR(100) NOT NULL,
  owner_jiacn VARCHAR(50) NOT NULL,
  agent_id VARCHAR(100) NOT NULL,
  runtime_instance_id VARCHAR(100) NOT NULL,
  message_type VARCHAR(32) NOT NULL,
  message_id VARCHAR(100) NOT NULL,
  command_id VARCHAR(100) NOT NULL,
  dispatch_message_id VARCHAR(100) NOT NULL,
  execution_ref VARCHAR(100) NOT NULL,
  grant_revision BIGINT NOT NULL,
  attempt INT NOT NULL,
  fencing_token VARCHAR(100) NOT NULL,
  sequence BIGINT NOT NULL,
  occurred_at BIGINT NOT NULL,
  semantic_hash BINARY(32) NOT NULL,
  payload_json MEDIUMBLOB NOT NULL,
  result_ref VARCHAR(100) NOT NULL,
  committed_version BIGINT NOT NULL,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  create_time BIGINT NOT NULL,
  update_time BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_execution_report_id (tenant_id,client_id,owner_jiacn,agent_id,report_id),
  UNIQUE KEY uk_execution_report_sequence (tenant_id,client_id,owner_jiacn,agent_id,command_id,attempt,sequence),
  KEY idx_execution_report_command (tenant_id,client_id,owner_jiacn,command_id,attempt,committed_version),
  KEY idx_execution_report_execution (tenant_id,client_id,owner_jiacn,execution_ref,agent_id),
  CONSTRAINT chk_execution_report_tenant CHECK (tenant_id='0'),
  CONSTRAINT chk_execution_report_numbers CHECK (grant_revision>0 AND attempt>0 AND sequence>0 AND occurred_at>0 AND committed_version>0),
  CONSTRAINT chk_execution_report_hash CHECK (OCTET_LENGTH(semantic_hash)=32),
  CONSTRAINT chk_execution_report_type CHECK (message_type IN ('work.progress','work.heartbeat','work.result','help.request','artifact.publish'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin
  COMMENT='Durable idempotent Protocol v1 report receipts; payload is a strict safe-field projection';
