CREATE TABLE IF NOT EXISTS agent_controlled_image_bridge_operation (
 id BIGINT NOT NULL AUTO_INCREMENT,
 owner_jiacn VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
 task_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 assignment_idempotency_key VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 wrapper_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 consent_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 expected_consent_version BIGINT NOT NULL,
 grant_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 grant_version BIGINT NOT NULL,
 assignment_revision BIGINT NOT NULL,
 authority_locator VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 execution_protocol_version INT NOT NULL DEFAULT 2,
 operation_grant_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL,
 created_at BIGINT NOT NULL,
 tenant_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
 client_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
 create_time BIGINT DEFAULT NULL, update_time BIGINT DEFAULT NULL,
 PRIMARY KEY(id),
 UNIQUE KEY uk_acibo_scope_key(tenant_id,client_id,owner_jiacn,task_id,assignment_idempotency_key),
 UNIQUE KEY uk_acibo_scope_consent(tenant_id,client_id,owner_jiacn,task_id,consent_id),
 UNIQUE KEY uk_acibo_scope_grant(tenant_id,client_id,owner_jiacn,task_id,grant_id),
 UNIQUE KEY uk_acibo_scope_operation_grant(tenant_id,client_id,owner_jiacn,task_id,operation_grant_id),
 CONSTRAINT chk_acibo_scope CHECK(tenant_id='0' AND owner_jiacn<>'0'),
 CONSTRAINT chk_acibo_hash CHECK(wrapper_digest REGEXP '^[0-9a-f]{64}$'),
 CONSTRAINT chk_acibo_consent CHECK(consent_id REGEXP '^consent_[0-9a-f]{32}$'),
 CONSTRAINT chk_acibo_locator CHECK(authority_locator=CONCAT('mmd-ci-v1:',consent_id)),
 CONSTRAINT chk_acibo_protocol CHECK((execution_protocol_version=2 AND operation_grant_id IS NULL) OR (execution_protocol_version=3 AND operation_grant_id REGEXP '^opgrant_[0-9a-f]{32}$')),
 CONSTRAINT chk_acibo_versions CHECK(expected_consent_version>0 AND grant_version>0 AND assignment_revision>=0),
 CONSTRAINT chk_acibo_time CHECK(created_at>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
