-- ECO-V0-W05 additive quote/claim projection. Synthetic preview fixture pricing only.
CREATE TABLE IF NOT EXISTS agent_task_bounty_quote (
  id BIGINT NOT NULL AUTO_INCREMENT,
  quote_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  task_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  agent_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  principal_type VARCHAR(20) COLLATE utf8mb4_0900_bin NOT NULL,
  principal_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  idempotency_key VARBINARY(36) NOT NULL,
  request_hash BINARY(32) NOT NULL,
  task_version BIGINT NOT NULL,
  price_book_version VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  task_input_hash VARCHAR(71) COLLATE utf8mb4_0900_bin NOT NULL,
  skill_set_hash VARCHAR(71) COLLATE utf8mb4_0900_bin NOT NULL,
  model_route_version VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  estimated_input_tokens BIGINT NOT NULL,
  estimated_cached_input_tokens BIGINT NOT NULL,
  estimated_output_tokens BIGINT NOT NULL,
  estimated_reasoning_tokens BIGINT NOT NULL,
  estimated_compute_micro BIGINT NOT NULL,
  worst_compute_micro BIGINT NOT NULL,
  platform_fee_micro BIGINT NOT NULL,
  gross_allocation_micro BIGINT NOT NULL,
  estimated_agent_payout_micro BIGINT NOT NULL,
  worst_agent_payout_micro BIGINT NOT NULL,
  minimum_accepted_payout_micro BIGINT NOT NULL,
  budget_headroom_micro BIGINT NOT NULL,
  verified_skill_match TINYINT(1) NOT NULL,
  advisory_ability_match TINYINT(1) NOT NULL,
  budget_covered TINYINT(1) NOT NULL,
  agent_ready TINYINT(1) NOT NULL,
  recommendation VARCHAR(20) COLLATE utf8mb4_0900_bin NOT NULL,
  reason_codes TEXT COLLATE utf8mb4_0900_bin NOT NULL,
  status VARCHAR(16) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'OPEN',
  expires_at BIGINT NOT NULL,
  claimed_at BIGINT NULL,
  tenant_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
  client_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
  create_time BIGINT NOT NULL,
  update_time BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_bounty_quote_id (tenant_id,client_id,quote_id),
  UNIQUE KEY uk_bounty_quote_actor_key (tenant_id,client_id,principal_type,principal_id,idempotency_key),
  KEY idx_bounty_quote_task (tenant_id,client_id,task_id,status,expires_at,id),
  CONSTRAINT chk_bounty_quote_hashes CHECK (OCTET_LENGTH(request_hash)=32 AND OCTET_LENGTH(idempotency_key)=36 AND task_input_hash LIKE 'sha256:%' AND skill_set_hash LIKE 'sha256:%'),
  CONSTRAINT chk_bounty_quote_amounts CHECK (task_version>=0 AND estimated_input_tokens>=0 AND estimated_cached_input_tokens>=0 AND estimated_output_tokens>=0 AND estimated_reasoning_tokens>=0 AND estimated_compute_micro>=0 AND worst_compute_micro>=estimated_compute_micro AND platform_fee_micro>=0 AND gross_allocation_micro>0 AND estimated_agent_payout_micro>=0 AND worst_agent_payout_micro>=0 AND minimum_accepted_payout_micro>=0 AND budget_headroom_micro>=0),
  CONSTRAINT chk_bounty_quote_state CHECK ((status='OPEN' AND claimed_at IS NULL) OR (status='CLAIMED' AND claimed_at IS NOT NULL AND claimed_at>0)),
  CONSTRAINT chk_bounty_quote_recommendation CHECK (recommendation IN ('recommended','caution','reject')),
  CONSTRAINT chk_bounty_quote_expiry CHECK (expires_at>create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS agent_task_bounty_claim_operation (
  id BIGINT NOT NULL AUTO_INCREMENT,
  principal_type VARCHAR(20) COLLATE utf8mb4_0900_bin NOT NULL,
  principal_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  idempotency_key VARBINARY(36) NOT NULL,
  request_hash BINARY(32) NOT NULL,
  task_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  agent_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  quote_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
  status VARCHAR(16) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'POSTING',
  receipt_task_version BIGINT NULL,
  claimed_at BIGINT NULL,
  tenant_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
  client_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
  create_time BIGINT NOT NULL,
  update_time BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_bounty_claim_actor_key (tenant_id,client_id,principal_type,principal_id,idempotency_key),
  UNIQUE KEY uk_bounty_claim_quote (tenant_id,client_id,quote_id),
  KEY idx_bounty_claim_task (tenant_id,client_id,task_id,status,id),
  CONSTRAINT chk_bounty_claim_hash CHECK (OCTET_LENGTH(request_hash)=32 AND OCTET_LENGTH(idempotency_key)=36),
  CONSTRAINT chk_bounty_claim_state CHECK ((status='POSTING' AND receipt_task_version IS NULL AND claimed_at IS NULL) OR (status='COMPLETED' AND receipt_task_version IS NOT NULL AND receipt_task_version>0 AND claimed_at IS NOT NULL AND claimed_at>0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
