-- 1.10 personal workspace. Additive owner-scoped upload metadata; no task artifact migration/backfill.
CREATE TABLE IF NOT EXISTS agent_personal_workspace_file (
  id BIGINT NOT NULL AUTO_INCREMENT,
  file_id VARCHAR(100) NOT NULL,
  owner_jiacn VARCHAR(50) NOT NULL,
  source_kind VARCHAR(24) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  media_family VARCHAR(32) NOT NULL,
  state VARCHAR(24) NOT NULL,
  metadata_revision BIGINT NOT NULL,
  latest_version INT NOT NULL,
  created_at BIGINT NOT NULL,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  create_time BIGINT DEFAULT NULL,
  update_time BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pws_file_scope (tenant_id, client_id, owner_jiacn, file_id),
  KEY idx_pws_file_list (tenant_id, client_id, owner_jiacn, state, created_at, file_id),
  KEY idx_pws_file_media (tenant_id, client_id, owner_jiacn, media_family, created_at, file_id),
  CONSTRAINT chk_pws_file_revision CHECK (metadata_revision >= 1 AND latest_version >= 1),
  CONSTRAINT chk_pws_file_state CHECK (state IN ('ACTIVE', 'TRASHED')),
  CONSTRAINT chk_pws_file_source CHECK (source_kind = 'UPLOAD')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS agent_personal_workspace_file_version (
  id BIGINT NOT NULL AUTO_INCREMENT,
  file_id VARCHAR(100) NOT NULL,
  owner_jiacn VARCHAR(50) NOT NULL,
  version INT NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  content_mime_type VARCHAR(127) NOT NULL,
  byte_length BIGINT NOT NULL,
  content_hash CHAR(64) NOT NULL,
  storage_uri VARCHAR(1000) NOT NULL,
  created_at BIGINT NOT NULL,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  create_time BIGINT DEFAULT NULL,
  update_time BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pws_version_scope (tenant_id, client_id, owner_jiacn, file_id, version),
  KEY idx_pws_version_list (tenant_id, client_id, owner_jiacn, file_id, version),
  CONSTRAINT chk_pws_version_positive CHECK (version >= 1 AND byte_length >= 0),
  CONSTRAINT chk_pws_version_hash CHECK (CHAR_LENGTH(content_hash)=64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS agent_personal_workspace_operation (
  id BIGINT NOT NULL AUTO_INCREMENT,
  operation_id VARCHAR(100) NOT NULL,
  owner_jiacn VARCHAR(50) NOT NULL,
  operation_type VARCHAR(40) NOT NULL,
  idempotency_key VARCHAR(100) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  state VARCHAR(32) NOT NULL,
  file_id VARCHAR(100) DEFAULT NULL,
  file_version INT DEFAULT NULL,
  error_code VARCHAR(80) DEFAULT NULL,
  created_at BIGINT NOT NULL,
  completed_at BIGINT DEFAULT NULL,
  tenant_id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  create_time BIGINT DEFAULT NULL,
  update_time BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pws_operation_key (tenant_id, client_id, owner_jiacn, operation_type, idempotency_key),
  UNIQUE KEY uk_pws_operation_id (tenant_id, client_id, operation_id),
  KEY idx_pws_operation_owner (tenant_id, client_id, owner_jiacn, operation_id),
  CONSTRAINT chk_pws_operation_hash CHECK (CHAR_LENGTH(request_hash)=64),
  CONSTRAINT chk_pws_operation_state CHECK (state IN ('PROCESSING','COMMITTED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
