CREATE TABLE IF NOT EXISTS agent_controlled_image_intent_operation_grant (
 id BIGINT NOT NULL AUTO_INCREMENT, operation_grant_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 owner_jiacn VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL, task_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 target_agent_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL, conversation_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 conversation_generation BIGINT NOT NULL, interaction_idempotency_key VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 request_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL, step_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 execution_intent_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL, baseline_grant_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 baseline_grant_version BIGINT NOT NULL, task_version BIGINT NOT NULL, assignment_revision BIGINT NOT NULL,
 requirement_revision BIGINT NOT NULL, requirement_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 operation VARCHAR(40) COLLATE utf8mb4_0900_bin NOT NULL, instruction_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 source_snapshot_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_snapshot_json JSON NOT NULL,
 owner_payload_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, consent_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 issue_idempotency_key VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL, issue_request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 state VARCHAR(20) COLLATE utf8mb4_0900_bin NOT NULL, version BIGINT NOT NULL,
 reserved_execution_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL, reserved_run_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL,
 consumed_lease_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL, revoke_idempotency_key VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL,
 revoke_request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, revoked_at BIGINT DEFAULT NULL, created_at BIGINT NOT NULL,
 tenant_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL, client_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
 create_time BIGINT DEFAULT NULL, update_time BIGINT DEFAULT NULL, PRIMARY KEY(id),
 UNIQUE KEY uk_aciiog_scope_id(tenant_id,client_id,owner_jiacn,task_id,operation_grant_id),
 UNIQUE KEY uk_aciiog_scope_issue(tenant_id,client_id,owner_jiacn,task_id,issue_idempotency_key),
 UNIQUE KEY uk_aciiog_scope_interaction(tenant_id,client_id,owner_jiacn,task_id,interaction_idempotency_key),
 UNIQUE KEY uk_aciiog_scope_intent(tenant_id,client_id,owner_jiacn,task_id,execution_intent_id),
 UNIQUE KEY uk_aciiog_scope_consent(tenant_id,client_id,owner_jiacn,task_id,consent_id),
 UNIQUE KEY uk_aciiog_scope_execution(tenant_id,client_id,owner_jiacn,reserved_execution_id),
 UNIQUE KEY uk_aciiog_scope_run(tenant_id,client_id,owner_jiacn,reserved_run_id),
 CONSTRAINT chk_aciiog_scope CHECK(tenant_id='0' AND owner_jiacn<>'0'),
 CONSTRAINT chk_aciiog_ids CHECK(operation_grant_id REGEXP '^opgrant_[0-9a-f]{32}$' AND consent_id REGEXP '^consent_[0-9a-f]{32}$'),
 CONSTRAINT chk_aciiog_hashes CHECK(requirement_sha256 REGEXP '^[0-9a-f]{64}$' AND instruction_sha256 REGEXP '^[0-9a-f]{64}$' AND source_snapshot_sha256 REGEXP '^[0-9a-f]{64}$' AND owner_payload_sha256 REGEXP '^[0-9a-f]{64}$' AND issue_request_digest REGEXP '^[0-9a-f]{64}$' AND (revoke_request_digest IS NULL OR revoke_request_digest REGEXP '^[0-9a-f]{64}$')),
 CONSTRAINT chk_aciiog_versions CHECK(conversation_generation>0 AND baseline_grant_version>0 AND task_version>=0 AND assignment_revision>=0 AND requirement_revision>0 AND version>0),
 CONSTRAINT chk_aciiog_operation CHECK(operation IN ('GENERATE_IMAGE','EDIT_IMAGE')),
 CONSTRAINT chk_aciiog_sources CHECK(JSON_TYPE(source_snapshot_json)='ARRAY' AND ((operation='GENERATE_IMAGE' AND JSON_LENGTH(source_snapshot_json) BETWEEN 0 AND 16) OR (operation='EDIT_IMAGE' AND JSON_LENGTH(source_snapshot_json)=1))),
 CONSTRAINT chk_aciiog_state CHECK(state IN ('AUTHORIZED','RESERVED','CONSUMED','REVOKED')),
 CONSTRAINT chk_aciiog_lifecycle CHECK((state='AUTHORIZED' AND reserved_execution_id IS NULL AND reserved_run_id IS NULL AND consumed_lease_id IS NULL AND revoke_idempotency_key IS NULL AND revoke_request_digest IS NULL AND revoked_at IS NULL) OR (state='RESERVED' AND reserved_execution_id IS NOT NULL AND reserved_run_id IS NOT NULL AND consumed_lease_id IS NULL AND revoke_idempotency_key IS NULL AND revoke_request_digest IS NULL AND revoked_at IS NULL) OR (state='CONSUMED' AND reserved_execution_id IS NOT NULL AND reserved_run_id IS NOT NULL AND consumed_lease_id IS NOT NULL AND revoke_idempotency_key IS NULL AND revoke_request_digest IS NULL AND revoked_at IS NULL) OR (state='REVOKED' AND ((reserved_execution_id IS NULL AND reserved_run_id IS NULL) OR (reserved_execution_id IS NOT NULL AND reserved_run_id IS NOT NULL)) AND consumed_lease_id IS NULL AND revoke_idempotency_key IS NOT NULL AND revoke_request_digest IS NOT NULL AND revoked_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE IF NOT EXISTS agent_controlled_image_execution_source_v3 (
 id BIGINT NOT NULL AUTO_INCREMENT, owner_jiacn VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
 execution_id VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL, input_ref VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL,
 input_ordinal INT NOT NULL, source_kind VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
 content_mime_type VARCHAR(100) COLLATE utf8mb4_0900_bin NOT NULL, byte_length BIGINT NOT NULL,
 content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_json JSON NOT NULL,
 file_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL, file_version INT DEFAULT NULL, purpose VARCHAR(20) COLLATE utf8mb4_0900_bin DEFAULT NULL,
 conversation_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL, conversation_generation BIGINT DEFAULT NULL,
 asset_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL, asset_revision BIGINT DEFAULT NULL,
 producer_request_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL, producer_request_revision BIGINT DEFAULT NULL,
 producer_step_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL, producer_execution_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL,
 producer_run_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL, producer_output_id VARCHAR(100) COLLATE utf8mb4_0900_bin DEFAULT NULL,
 created_at BIGINT NOT NULL, tenant_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL,
 client_id VARCHAR(50) COLLATE utf8mb4_0900_bin NOT NULL, create_time BIGINT DEFAULT NULL, update_time BIGINT DEFAULT NULL,
 PRIMARY KEY(id), UNIQUE KEY uk_acies_scope_ref(tenant_id,client_id,owner_jiacn,execution_id,input_ref),
 UNIQUE KEY uk_acies_scope_ordinal(tenant_id,client_id,owner_jiacn,execution_id,input_ordinal),
 CONSTRAINT chk_acies_scope CHECK(tenant_id='0' AND owner_jiacn<>'0'),
 CONSTRAINT chk_acies_common CHECK(input_ordinal BETWEEN 1 AND 16 AND content_mime_type IN ('image/jpeg','image/png') AND byte_length>0 AND content_sha256 REGEXP '^[0-9a-f]{64}$'),
 CONSTRAINT chk_acies_union CHECK((source_kind='TASK_LINKED_WORKSPACE_VERSION' AND file_id IS NOT NULL AND file_version>0 AND purpose IN ('INPUT','REFERENCE') AND conversation_id IS NULL AND conversation_generation IS NULL AND asset_id IS NULL AND asset_revision IS NULL AND producer_request_id IS NULL AND producer_request_revision IS NULL AND producer_step_id IS NULL AND producer_execution_id IS NULL AND producer_run_id IS NULL AND producer_output_id IS NULL) OR (source_kind='CURRENT_CONVERSATION_ASSET' AND file_id IS NULL AND file_version IS NULL AND purpose IS NULL AND conversation_id IS NOT NULL AND conversation_generation>0 AND asset_id IS NOT NULL AND asset_revision>0 AND producer_request_id IS NOT NULL AND producer_request_revision>0 AND producer_step_id IS NOT NULL AND producer_execution_id IS NOT NULL AND producer_run_id IS NOT NULL AND producer_output_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
