/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./components/Chat.vue')['default']
    GiftPay: typeof import('./components/GiftPay.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OrderList: typeof import('./components/OrderList.vue')['default']
    Phrase: typeof import('./components/Phrase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortLink: typeof import('./components/ShortLink.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
    TaskAdd: typeof import('./components/TaskAdd.vue')['default']
    TaskHistory: typeof import('./components/TaskHistory.vue')['default']
    TaskIndex: typeof import('./components/TaskIndex.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
    VoteTick: typeof import('./components/VoteTick.vue')['default']
  }
}
