CREATE TABLE wx_mp_info (
  acid int unsigned NOT NULL AUTO_INCREMENT,
  client_id varchar(32) DEFAULT NULL COMMENT '应用标识码',
  token varchar(32) NOT NULL COMMENT '令牌',
  access_token varchar(1000) DEFAULT NULL,
  encodingaeskey varchar(255) NOT NULL COMMENT '消息加解密密钥',
  level tinyint unsigned NOT NULL COMMENT '认证类别 1普通订阅号 2普通服务号 3认证订阅号 4认证服务号/认证媒体/政府订阅号',
  name varchar(30) NOT NULL COMMENT '公众号名称',
  account varchar(30) NOT NULL COMMENT '公众号帐号',
  original varchar(50) NOT NULL COMMENT '原始ID',
  signature varchar(100) DEFAULT NULL COMMENT '介绍',
  country varchar(10) DEFAULT NULL COMMENT '国家',
  province varchar(3) DEFAULT NULL COMMENT '省份',
  city varchar(15) DEFAULT NULL COMMENT '城市',
  username varchar(30) NOT NULL COMMENT '登录账号',
  password varchar(32) NOT NULL COMMENT '登录密码',
  create_time bigint DEFAULT NULL,
  update_time bigint unsigned DEFAULT NULL,
  status int DEFAULT '1' COMMENT '状态 1有效 0无效',
  appid varchar(50) NOT NULL COMMENT '开发者ID',
  secret varchar(50) NOT NULL COMMENT '开发者密码',
  styleid int unsigned DEFAULT NULL,
  subscribeurl varchar(120) DEFAULT NULL,
  auth_refresh_token varchar(255) DEFAULT NULL,
  PRIMARY KEY (acid),
  KEY idx_key (appid) USING BTREE
);